provider: datadog
major-version: 4
upstreamProviderOrg: DataDog
lint: false
makeTemplate: bridged
env:
  DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
  DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
pulumiConvert: 1
registryDocs: true
plugins:
  - name: terraform
    version: "1.0.16"
    kind: converter
integrationTestProvider: true
