// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog
{
    public static class GetStatusPage
    {
        /// <summary>
        /// Use this data source to retrieve information about an existing Datadog status page.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Datadog = Pulumi.Datadog;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var acmeStatusPage = Datadog.GetStatusPage.Invoke(new()
        ///     {
        ///         Id = "8fd8c3ef-07b1-4441-b52a-7e42d8474d5c",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetStatusPageResult> InvokeAsync(GetStatusPageArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetStatusPageResult>("datadog:index/getStatusPage:getStatusPage", args ?? new GetStatusPageArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to retrieve information about an existing Datadog status page.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Datadog = Pulumi.Datadog;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var acmeStatusPage = Datadog.GetStatusPage.Invoke(new()
        ///     {
        ///         Id = "8fd8c3ef-07b1-4441-b52a-7e42d8474d5c",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetStatusPageResult> Invoke(GetStatusPageInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetStatusPageResult>("datadog:index/getStatusPage:getStatusPage", args ?? new GetStatusPageInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to retrieve information about an existing Datadog status page.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Datadog = Pulumi.Datadog;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var acmeStatusPage = Datadog.GetStatusPage.Invoke(new()
        ///     {
        ///         Id = "8fd8c3ef-07b1-4441-b52a-7e42d8474d5c",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetStatusPageResult> Invoke(GetStatusPageInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetStatusPageResult>("datadog:index/getStatusPage:getStatusPage", args ?? new GetStatusPageInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetStatusPageArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the status page.
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetStatusPageArgs()
        {
        }
        public static new GetStatusPageArgs Empty => new GetStatusPageArgs();
    }

    public sealed class GetStatusPageInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the status page.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetStatusPageInvokeArgs()
        {
        }
        public static new GetStatusPageInvokeArgs Empty => new GetStatusPageInvokeArgs();
    }


    [OutputType]
    public sealed class GetStatusPageResult
    {
        /// <summary>
        /// The company logo displayed on the status page.
        /// </summary>
        public readonly string CompanyLogo;
        /// <summary>
        /// Timestamp when the status page was created.
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// The custom domain configured for the status page, if any.
        /// </summary>
        public readonly string CustomDomain;
        /// <summary>
        /// Whether the custom domain is enabled for the status page.
        /// </summary>
        public readonly bool CustomDomainEnabled;
        /// <summary>
        /// The subdomain prefix used to build the status page's URL.
        /// </summary>
        public readonly string DomainPrefix;
        /// <summary>
        /// The header image included in subscriber emails.
        /// </summary>
        public readonly string EmailHeaderImage;
        /// <summary>
        /// Whether the status page is published.
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// The favicon displayed for the status page.
        /// </summary>
        public readonly string Favicon;
        /// <summary>
        /// The ID of the status page.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Timestamp when the status page was last modified.
        /// </summary>
        public readonly string ModifiedAt;
        /// <summary>
        /// The name of the status page.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The URL of the status page.
        /// </summary>
        public readonly string PageUrl;
        /// <summary>
        /// The icon used for the status page's Slack app integration.
        /// </summary>
        public readonly string SlackAppIcon;
        /// <summary>
        /// Whether Slack subscriber notifications are enabled for the status page.
        /// </summary>
        public readonly bool SlackSubscriptionsEnabled;
        /// <summary>
        /// Whether subscriber notifications are enabled for the status page.
        /// </summary>
        public readonly bool SubscriptionsEnabled;
        /// <summary>
        /// The type of the status page.
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// How component statuses are visualized on the page.
        /// </summary>
        public readonly string VisualizationType;

        [OutputConstructor]
        private GetStatusPageResult(
            string companyLogo,

            string createdAt,

            string customDomain,

            bool customDomainEnabled,

            string domainPrefix,

            string emailHeaderImage,

            bool enabled,

            string favicon,

            string id,

            string modifiedAt,

            string name,

            string pageUrl,

            string slackAppIcon,

            bool slackSubscriptionsEnabled,

            bool subscriptionsEnabled,

            string type,

            string visualizationType)
        {
            CompanyLogo = companyLogo;
            CreatedAt = createdAt;
            CustomDomain = customDomain;
            CustomDomainEnabled = customDomainEnabled;
            DomainPrefix = domainPrefix;
            EmailHeaderImage = emailHeaderImage;
            Enabled = enabled;
            Favicon = favicon;
            Id = id;
            ModifiedAt = modifiedAt;
            Name = name;
            PageUrl = pageUrl;
            SlackAppIcon = slackAppIcon;
            SlackSubscriptionsEnabled = slackSubscriptionsEnabled;
            SubscriptionsEnabled = subscriptionsEnabled;
            Type = type;
            VisualizationType = visualizationType;
        }
    }
}
