// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Databricks
{
    /// <summary>
    /// Provides a Datadog Databricks integration account resource. Manages a Databricks workspace connection used for Data Jobs Monitoring, Cloud Cost Management, Data Observability, and related Databricks-driven products.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Datadog = Pulumi.Datadog;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Create a Databricks integration account using OAuth (recommended).
    ///     var oauthExample = new Datadog.Databricks.IntegrationAccount("oauth_example", new()
    ///     {
    ///         Name = "databricks-prod",
    ///         WorkspaceUrl = "https://your-workspace.cloud.databricks.com",
    ///         AuthConfig = new[]
    ///         {
    ///             
    ///             {
    ///                 { "oauth", new[]
    ///                 {
    ///                     
    ///                     {
    ///                         { "clientId", "abc123def456" },
    ///                         { "clientSecret", "secret-value" },
    ///                         { "databricksAccountId", "11111111-2222-3333-4444-555555555555" },
    ///                     },
    ///                 } },
    ///             },
    ///         },
    ///         DjmEnabled = true,
    ///         ServerlessJobsEnabled = true,
    ///     });
    /// 
    ///     // Alternative: Databricks integration account using a Personal Access Token (PAT).
    ///     // OAuth is preferred for new deployments; PAT is kept for backwards compatibility.
    ///     var patExample = new Datadog.Databricks.IntegrationAccount("pat_example", new()
    ///     {
    ///         Name = "databricks-legacy",
    ///         WorkspaceUrl = "https://your-workspace.cloud.databricks.com",
    ///         AuthConfig = new[]
    ///         {
    ///             
    ///             {
    ///                 { "pat", new[]
    ///                 {
    ///                     
    ///                     {
    ///                         { "token", "dapi-..." },
    ///                     },
    ///                 } },
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// The `pulumi import` command can be used, for example:
    /// 
    /// ```sh
    /// $ pulumi import datadog:databricks/integrationAccount:IntegrationAccount example "&lt;ACCOUNT_ID&gt;"
    /// ```
    /// </summary>
    [DatadogResourceType("datadog:databricks/integrationAccount:IntegrationAccount")]
    public partial class IntegrationAccount : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Configure how Datadog authenticates to your Databricks workspace. Exactly one of `Oauth` or `Pat` must be provided.
        /// </summary>
        [Output("authConfig")]
        public Output<Outputs.IntegrationAccountAuthConfig?> AuthConfig { get; private set; } = null!;

        /// <summary>
        /// Enable Cloud Cost Management to collect cost data from Databricks System Tables. Requires `SystemTablesSqlWarehouseId`. Defaults to `False`.
        /// </summary>
        [Output("ccmEnabled")]
        public Output<bool> CcmEnabled { get; private set; } = null!;

        /// <summary>
        /// Datadog API Key ID used for the Data Jobs Monitoring init script when managed by Datadog.
        /// </summary>
        [Output("ddApiKeyId")]
        public Output<string?> DdApiKeyId { get; private set; } = null!;

        /// <summary>
        /// Datadog API Key value (not ID) used for the Data Jobs Monitoring init script when managed by Datadog. This value is write-only; changes made outside of Terraform will not be drift-detected.
        /// </summary>
        [Output("ddApiKeySecret")]
        public Output<string?> DdApiKeySecret { get; private set; } = null!;

        /// <summary>
        /// When enabled, Datadog installs and manages the Agent using a cluster policy and Unity Catalog Volume. Requires a Unity Catalog-enabled workspace with DBR 13.3 LTS+ and `UcVolumePath`. Defaults to `False`.
        /// </summary>
        [Output("djmClusterPolicyEnabled")]
        public Output<bool> DjmClusterPolicyEnabled { get; private set; } = null!;

        /// <summary>
        /// Enable Data Jobs Monitoring for this workspace. Defaults to true. Defaults to `True`.
        /// </summary>
        [Output("djmEnabled")]
        public Output<bool> DjmEnabled { get; private set; } = null!;

        /// <summary>
        /// When enabled, Datadog installs and manages the Agent with a global init script in the workspace. Installation can take up to 15 minutes. Requires Workspace Admin permissions. Defaults to `False`.
        /// </summary>
        [Output("djmGlobalInitScriptEnabled")]
        public Output<bool> DjmGlobalInitScriptEnabled { get; private set; } = null!;

        /// <summary>
        /// Cron schedule controlling how often Datadog crawls the Databricks warehouse for metadata. Defaults to hourly. Defaults to `"0 * * * *"`.
        /// </summary>
        [Output("doCrawlersCron")]
        public Output<string> DoCrawlersCron { get; private set; } = null!;

        /// <summary>
        /// Enable Data Observability to collect data for viewing in Datadog Data Observability. Defaults to `False`.
        /// </summary>
        [Output("doEnabled")]
        public Output<bool> DoEnabled { get; private set; } = null!;

        /// <summary>
        /// Name of the Databricks model serving endpoint to monitor.
        /// </summary>
        [Output("modelServingEndpointName")]
        public Output<string?> ModelServingEndpointName { get; private set; } = null!;

        /// <summary>
        /// Retrieve health and usage metrics from Databricks model serving endpoints. Defaults to `False`.
        /// </summary>
        [Output("modelServingMetricsEnabled")]
        public Output<bool> ModelServingMetricsEnabled { get; private set; } = null!;

        /// <summary>
        /// A human-readable name for the account.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Run Datadog crawlers behind a Private Action Runner instead of from Datadog's network.
        /// </summary>
        [Output("privateActionRunnerConfiguration")]
        public Output<Outputs.IntegrationAccountPrivateActionRunnerConfiguration?> PrivateActionRunnerConfiguration { get; private set; } = null!;

        /// <summary>
        /// Collect GPU metrics from Databricks clusters when using a Datadog-managed init script. Defaults to `False`.
        /// </summary>
        [Output("scriptGpumEnabled")]
        public Output<bool> ScriptGpumEnabled { get; private set; } = null!;

        /// <summary>
        /// Collect driver and worker logs from Databricks clusters when using a Datadog-managed init script. Defaults to `False`.
        /// </summary>
        [Output("scriptLogsEnabled")]
        public Output<bool> ScriptLogsEnabled { get; private set; } = null!;

        /// <summary>
        /// Serverless opt-in for Data Jobs Monitoring. Defaults to true. Defaults to `True`.
        /// </summary>
        [Output("serverlessJobsEnabled")]
        public Output<bool> ServerlessJobsEnabled { get; private set; } = null!;

        /// <summary>
        /// SQL Warehouse ID for querying Databricks System Tables. Required for Cloud Cost Management.
        /// </summary>
        [Output("systemTablesSqlWarehouseId")]
        public Output<string?> SystemTablesSqlWarehouseId { get; private set; } = null!;

        /// <summary>
        /// Enable table lineage tracking for Databricks tables. Defaults to `False`.
        /// </summary>
        [Output("tableLineageEnabled")]
        public Output<bool> TableLineageEnabled { get; private set; } = null!;

        /// <summary>
        /// Unity Catalog volume path in `catalog.schema.volume` format where the Datadog init script will be stored (e.g. `main.default.datadog_volume`). Required when `DjmClusterPolicyEnabled` is true.
        /// </summary>
        [Output("ucVolumePath")]
        public Output<string?> UcVolumePath { get; private set; } = null!;

        /// <summary>
        /// The URL of your Databricks workspace (e.g., https://your-workspace.cloud.databricks.com).
        /// </summary>
        [Output("workspaceUrl")]
        public Output<string> WorkspaceUrl { get; private set; } = null!;


        /// <summary>
        /// Create a IntegrationAccount resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public IntegrationAccount(string name, IntegrationAccountArgs args, CustomResourceOptions? options = null)
            : base("datadog:databricks/integrationAccount:IntegrationAccount", name, args ?? new IntegrationAccountArgs(), MakeResourceOptions(options, ""))
        {
        }

        private IntegrationAccount(string name, Input<string> id, IntegrationAccountState? state = null, CustomResourceOptions? options = null)
            : base("datadog:databricks/integrationAccount:IntegrationAccount", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "ddApiKeySecret",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing IntegrationAccount resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static IntegrationAccount Get(string name, Input<string> id, IntegrationAccountState? state = null, CustomResourceOptions? options = null)
        {
            return new IntegrationAccount(name, id, state, options);
        }
    }

    public sealed class IntegrationAccountArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Configure how Datadog authenticates to your Databricks workspace. Exactly one of `Oauth` or `Pat` must be provided.
        /// </summary>
        [Input("authConfig")]
        public Input<Inputs.IntegrationAccountAuthConfigArgs>? AuthConfig { get; set; }

        /// <summary>
        /// Enable Cloud Cost Management to collect cost data from Databricks System Tables. Requires `SystemTablesSqlWarehouseId`. Defaults to `False`.
        /// </summary>
        [Input("ccmEnabled")]
        public Input<bool>? CcmEnabled { get; set; }

        /// <summary>
        /// Datadog API Key ID used for the Data Jobs Monitoring init script when managed by Datadog.
        /// </summary>
        [Input("ddApiKeyId")]
        public Input<string>? DdApiKeyId { get; set; }

        [Input("ddApiKeySecret")]
        private Input<string>? _ddApiKeySecret;

        /// <summary>
        /// Datadog API Key value (not ID) used for the Data Jobs Monitoring init script when managed by Datadog. This value is write-only; changes made outside of Terraform will not be drift-detected.
        /// </summary>
        public Input<string>? DdApiKeySecret
        {
            get => _ddApiKeySecret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _ddApiKeySecret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// When enabled, Datadog installs and manages the Agent using a cluster policy and Unity Catalog Volume. Requires a Unity Catalog-enabled workspace with DBR 13.3 LTS+ and `UcVolumePath`. Defaults to `False`.
        /// </summary>
        [Input("djmClusterPolicyEnabled")]
        public Input<bool>? DjmClusterPolicyEnabled { get; set; }

        /// <summary>
        /// Enable Data Jobs Monitoring for this workspace. Defaults to true. Defaults to `True`.
        /// </summary>
        [Input("djmEnabled")]
        public Input<bool>? DjmEnabled { get; set; }

        /// <summary>
        /// When enabled, Datadog installs and manages the Agent with a global init script in the workspace. Installation can take up to 15 minutes. Requires Workspace Admin permissions. Defaults to `False`.
        /// </summary>
        [Input("djmGlobalInitScriptEnabled")]
        public Input<bool>? DjmGlobalInitScriptEnabled { get; set; }

        /// <summary>
        /// Cron schedule controlling how often Datadog crawls the Databricks warehouse for metadata. Defaults to hourly. Defaults to `"0 * * * *"`.
        /// </summary>
        [Input("doCrawlersCron")]
        public Input<string>? DoCrawlersCron { get; set; }

        /// <summary>
        /// Enable Data Observability to collect data for viewing in Datadog Data Observability. Defaults to `False`.
        /// </summary>
        [Input("doEnabled")]
        public Input<bool>? DoEnabled { get; set; }

        /// <summary>
        /// Name of the Databricks model serving endpoint to monitor.
        /// </summary>
        [Input("modelServingEndpointName")]
        public Input<string>? ModelServingEndpointName { get; set; }

        /// <summary>
        /// Retrieve health and usage metrics from Databricks model serving endpoints. Defaults to `False`.
        /// </summary>
        [Input("modelServingMetricsEnabled")]
        public Input<bool>? ModelServingMetricsEnabled { get; set; }

        /// <summary>
        /// A human-readable name for the account.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Run Datadog crawlers behind a Private Action Runner instead of from Datadog's network.
        /// </summary>
        [Input("privateActionRunnerConfiguration")]
        public Input<Inputs.IntegrationAccountPrivateActionRunnerConfigurationArgs>? PrivateActionRunnerConfiguration { get; set; }

        /// <summary>
        /// Collect GPU metrics from Databricks clusters when using a Datadog-managed init script. Defaults to `False`.
        /// </summary>
        [Input("scriptGpumEnabled")]
        public Input<bool>? ScriptGpumEnabled { get; set; }

        /// <summary>
        /// Collect driver and worker logs from Databricks clusters when using a Datadog-managed init script. Defaults to `False`.
        /// </summary>
        [Input("scriptLogsEnabled")]
        public Input<bool>? ScriptLogsEnabled { get; set; }

        /// <summary>
        /// Serverless opt-in for Data Jobs Monitoring. Defaults to true. Defaults to `True`.
        /// </summary>
        [Input("serverlessJobsEnabled")]
        public Input<bool>? ServerlessJobsEnabled { get; set; }

        /// <summary>
        /// SQL Warehouse ID for querying Databricks System Tables. Required for Cloud Cost Management.
        /// </summary>
        [Input("systemTablesSqlWarehouseId")]
        public Input<string>? SystemTablesSqlWarehouseId { get; set; }

        /// <summary>
        /// Enable table lineage tracking for Databricks tables. Defaults to `False`.
        /// </summary>
        [Input("tableLineageEnabled")]
        public Input<bool>? TableLineageEnabled { get; set; }

        /// <summary>
        /// Unity Catalog volume path in `catalog.schema.volume` format where the Datadog init script will be stored (e.g. `main.default.datadog_volume`). Required when `DjmClusterPolicyEnabled` is true.
        /// </summary>
        [Input("ucVolumePath")]
        public Input<string>? UcVolumePath { get; set; }

        /// <summary>
        /// The URL of your Databricks workspace (e.g., https://your-workspace.cloud.databricks.com).
        /// </summary>
        [Input("workspaceUrl", required: true)]
        public Input<string> WorkspaceUrl { get; set; } = null!;

        public IntegrationAccountArgs()
        {
        }
        public static new IntegrationAccountArgs Empty => new IntegrationAccountArgs();
    }

    public sealed class IntegrationAccountState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Configure how Datadog authenticates to your Databricks workspace. Exactly one of `Oauth` or `Pat` must be provided.
        /// </summary>
        [Input("authConfig")]
        public Input<Inputs.IntegrationAccountAuthConfigGetArgs>? AuthConfig { get; set; }

        /// <summary>
        /// Enable Cloud Cost Management to collect cost data from Databricks System Tables. Requires `SystemTablesSqlWarehouseId`. Defaults to `False`.
        /// </summary>
        [Input("ccmEnabled")]
        public Input<bool>? CcmEnabled { get; set; }

        /// <summary>
        /// Datadog API Key ID used for the Data Jobs Monitoring init script when managed by Datadog.
        /// </summary>
        [Input("ddApiKeyId")]
        public Input<string>? DdApiKeyId { get; set; }

        [Input("ddApiKeySecret")]
        private Input<string>? _ddApiKeySecret;

        /// <summary>
        /// Datadog API Key value (not ID) used for the Data Jobs Monitoring init script when managed by Datadog. This value is write-only; changes made outside of Terraform will not be drift-detected.
        /// </summary>
        public Input<string>? DdApiKeySecret
        {
            get => _ddApiKeySecret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _ddApiKeySecret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// When enabled, Datadog installs and manages the Agent using a cluster policy and Unity Catalog Volume. Requires a Unity Catalog-enabled workspace with DBR 13.3 LTS+ and `UcVolumePath`. Defaults to `False`.
        /// </summary>
        [Input("djmClusterPolicyEnabled")]
        public Input<bool>? DjmClusterPolicyEnabled { get; set; }

        /// <summary>
        /// Enable Data Jobs Monitoring for this workspace. Defaults to true. Defaults to `True`.
        /// </summary>
        [Input("djmEnabled")]
        public Input<bool>? DjmEnabled { get; set; }

        /// <summary>
        /// When enabled, Datadog installs and manages the Agent with a global init script in the workspace. Installation can take up to 15 minutes. Requires Workspace Admin permissions. Defaults to `False`.
        /// </summary>
        [Input("djmGlobalInitScriptEnabled")]
        public Input<bool>? DjmGlobalInitScriptEnabled { get; set; }

        /// <summary>
        /// Cron schedule controlling how often Datadog crawls the Databricks warehouse for metadata. Defaults to hourly. Defaults to `"0 * * * *"`.
        /// </summary>
        [Input("doCrawlersCron")]
        public Input<string>? DoCrawlersCron { get; set; }

        /// <summary>
        /// Enable Data Observability to collect data for viewing in Datadog Data Observability. Defaults to `False`.
        /// </summary>
        [Input("doEnabled")]
        public Input<bool>? DoEnabled { get; set; }

        /// <summary>
        /// Name of the Databricks model serving endpoint to monitor.
        /// </summary>
        [Input("modelServingEndpointName")]
        public Input<string>? ModelServingEndpointName { get; set; }

        /// <summary>
        /// Retrieve health and usage metrics from Databricks model serving endpoints. Defaults to `False`.
        /// </summary>
        [Input("modelServingMetricsEnabled")]
        public Input<bool>? ModelServingMetricsEnabled { get; set; }

        /// <summary>
        /// A human-readable name for the account.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Run Datadog crawlers behind a Private Action Runner instead of from Datadog's network.
        /// </summary>
        [Input("privateActionRunnerConfiguration")]
        public Input<Inputs.IntegrationAccountPrivateActionRunnerConfigurationGetArgs>? PrivateActionRunnerConfiguration { get; set; }

        /// <summary>
        /// Collect GPU metrics from Databricks clusters when using a Datadog-managed init script. Defaults to `False`.
        /// </summary>
        [Input("scriptGpumEnabled")]
        public Input<bool>? ScriptGpumEnabled { get; set; }

        /// <summary>
        /// Collect driver and worker logs from Databricks clusters when using a Datadog-managed init script. Defaults to `False`.
        /// </summary>
        [Input("scriptLogsEnabled")]
        public Input<bool>? ScriptLogsEnabled { get; set; }

        /// <summary>
        /// Serverless opt-in for Data Jobs Monitoring. Defaults to true. Defaults to `True`.
        /// </summary>
        [Input("serverlessJobsEnabled")]
        public Input<bool>? ServerlessJobsEnabled { get; set; }

        /// <summary>
        /// SQL Warehouse ID for querying Databricks System Tables. Required for Cloud Cost Management.
        /// </summary>
        [Input("systemTablesSqlWarehouseId")]
        public Input<string>? SystemTablesSqlWarehouseId { get; set; }

        /// <summary>
        /// Enable table lineage tracking for Databricks tables. Defaults to `False`.
        /// </summary>
        [Input("tableLineageEnabled")]
        public Input<bool>? TableLineageEnabled { get; set; }

        /// <summary>
        /// Unity Catalog volume path in `catalog.schema.volume` format where the Datadog init script will be stored (e.g. `main.default.datadog_volume`). Required when `DjmClusterPolicyEnabled` is true.
        /// </summary>
        [Input("ucVolumePath")]
        public Input<string>? UcVolumePath { get; set; }

        /// <summary>
        /// The URL of your Databricks workspace (e.g., https://your-workspace.cloud.databricks.com).
        /// </summary>
        [Input("workspaceUrl")]
        public Input<string>? WorkspaceUrl { get; set; }

        public IntegrationAccountState()
        {
        }
        public static new IntegrationAccountState Empty => new IntegrationAccountState();
    }
}
