// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Outputs
{

    [OutputType]
    public sealed class DashboardV2WidgetGroupDefinitionWidgetWildcardDefinitionRequestTimeseriesRequestQueryUserJourneyQuerySearchFiltersAudienceFilters
    {
        /// <summary>
        /// Product Analytics audience account subqueries.
        /// </summary>
        public readonly ImmutableArray<Outputs.DashboardV2WidgetGroupDefinitionWidgetWildcardDefinitionRequestTimeseriesRequestQueryUserJourneyQuerySearchFiltersAudienceFiltersAccount> Accounts;
        /// <summary>
        /// An optional filter condition applied to the audience subquery.
        /// </summary>
        public readonly string? FilterCondition;
        /// <summary>
        /// Product Analytics audience segment subqueries.
        /// </summary>
        public readonly ImmutableArray<Outputs.DashboardV2WidgetGroupDefinitionWidgetWildcardDefinitionRequestTimeseriesRequestQueryUserJourneyQuerySearchFiltersAudienceFiltersSegment> Segments;
        /// <summary>
        /// Product Analytics audience user subqueries.
        /// </summary>
        public readonly ImmutableArray<Outputs.DashboardV2WidgetGroupDefinitionWidgetWildcardDefinitionRequestTimeseriesRequestQueryUserJourneyQuerySearchFiltersAudienceFiltersUser> Users;

        [OutputConstructor]
        private DashboardV2WidgetGroupDefinitionWidgetWildcardDefinitionRequestTimeseriesRequestQueryUserJourneyQuerySearchFiltersAudienceFilters(
            ImmutableArray<Outputs.DashboardV2WidgetGroupDefinitionWidgetWildcardDefinitionRequestTimeseriesRequestQueryUserJourneyQuerySearchFiltersAudienceFiltersAccount> accounts,

            string? filterCondition,

            ImmutableArray<Outputs.DashboardV2WidgetGroupDefinitionWidgetWildcardDefinitionRequestTimeseriesRequestQueryUserJourneyQuerySearchFiltersAudienceFiltersSegment> segments,

            ImmutableArray<Outputs.DashboardV2WidgetGroupDefinitionWidgetWildcardDefinitionRequestTimeseriesRequestQueryUserJourneyQuerySearchFiltersAudienceFiltersUser> users)
        {
            Accounts = accounts;
            FilterCondition = filterCondition;
            Segments = segments;
            Users = users;
        }
    }
}
