// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Outputs
{

    [OutputType]
    public sealed class DashboardWidgetSplitGraphDefinitionSourceWidgetDefinitionQueryValueDefinitionRequestQueryEventQuery
    {
        /// <summary>
        /// The compute options.
        /// </summary>
        public readonly ImmutableArray<Outputs.DashboardWidgetSplitGraphDefinitionSourceWidgetDefinitionQueryValueDefinitionRequestQueryEventQueryCompute> Computes;
        /// <summary>
        /// The data source for APM Dependency Stats queries. Valid values are `apm_dependency_stats`.
        /// </summary>
        public readonly string DataSource;
        /// <summary>
        /// Multiple `group_by` blocks are allowed using the structure below.
        /// </summary>
        public readonly ImmutableArray<Outputs.DashboardWidgetSplitGraphDefinitionSourceWidgetDefinitionQueryValueDefinitionRequestQueryEventQueryGroupBy> GroupBies;
        /// <summary>
        /// An array of index names to query in the stream.
        /// </summary>
        public readonly ImmutableArray<string> Indexes;
        /// <summary>
        /// The name of the variable.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The search options.
        /// </summary>
        public readonly Outputs.DashboardWidgetSplitGraphDefinitionSourceWidgetDefinitionQueryValueDefinitionRequestQueryEventQuerySearch? Search;
        /// <summary>
        /// Storage location (private beta).
        /// </summary>
        public readonly string? Storage;

        [OutputConstructor]
        private DashboardWidgetSplitGraphDefinitionSourceWidgetDefinitionQueryValueDefinitionRequestQueryEventQuery(
            ImmutableArray<Outputs.DashboardWidgetSplitGraphDefinitionSourceWidgetDefinitionQueryValueDefinitionRequestQueryEventQueryCompute> computes,

            string dataSource,

            ImmutableArray<Outputs.DashboardWidgetSplitGraphDefinitionSourceWidgetDefinitionQueryValueDefinitionRequestQueryEventQueryGroupBy> groupBies,

            ImmutableArray<string> indexes,

            string name,

            Outputs.DashboardWidgetSplitGraphDefinitionSourceWidgetDefinitionQueryValueDefinitionRequestQueryEventQuerySearch? search,

            string? storage)
        {
            Computes = computes;
            DataSource = dataSource;
            GroupBies = groupBies;
            Indexes = indexes;
            Name = name;
            Search = search;
            Storage = storage;
        }
    }
}
