// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Outputs
{

    [OutputType]
    public sealed class DashboardWidgetServicemapDefinition
    {
        public readonly ImmutableArray<Outputs.DashboardWidgetServicemapDefinitionCustomLink> CustomLinks;
        public readonly ImmutableArray<string> Filters;
        public readonly string Service;
        /// <summary>
        /// The title of the dashboard.
        /// </summary>
        public readonly string? Title;
        public readonly string? TitleAlign;
        public readonly string? TitleSize;

        [OutputConstructor]
        private DashboardWidgetServicemapDefinition(
            ImmutableArray<Outputs.DashboardWidgetServicemapDefinitionCustomLink> customLinks,

            ImmutableArray<string> filters,

            string service,

            string? title,

            string? titleAlign,

            string? titleSize)
        {
            CustomLinks = customLinks;
            Filters = filters;
            Service = service;
            Title = title;
            TitleAlign = titleAlign;
            TitleSize = titleSize;
        }
    }
}
