// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Outputs
{

    [OutputType]
    public sealed class DashboardV2WidgetHostmapDefinitionRequestFillQueryUserJourneyQuery
    {
        /// <summary>
        /// Compute configuration for the User Journey query.
        /// </summary>
        public readonly Outputs.DashboardV2WidgetHostmapDefinitionRequestFillQueryUserJourneyQueryCompute Compute;
        /// <summary>
        /// Data source for User Journey queries. Valid values are `ProductAnalyticsJourney`.
        /// </summary>
        public readonly string DataSource;
        /// <summary>
        /// Group by configuration for the User Journey query.
        /// </summary>
        public readonly ImmutableArray<Outputs.DashboardV2WidgetHostmapDefinitionRequestFillQueryUserJourneyQueryGroupBy> GroupBies;
        /// <summary>
        /// Name of the query for use in formulas.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// User journey search configuration.
        /// </summary>
        public readonly Outputs.DashboardV2WidgetHostmapDefinitionRequestFillQueryUserJourneyQuerySearch Search;

        [OutputConstructor]
        private DashboardV2WidgetHostmapDefinitionRequestFillQueryUserJourneyQuery(
            Outputs.DashboardV2WidgetHostmapDefinitionRequestFillQueryUserJourneyQueryCompute compute,

            string dataSource,

            ImmutableArray<Outputs.DashboardV2WidgetHostmapDefinitionRequestFillQueryUserJourneyQueryGroupBy> groupBies,

            string name,

            Outputs.DashboardV2WidgetHostmapDefinitionRequestFillQueryUserJourneyQuerySearch search)
        {
            Compute = compute;
            DataSource = dataSource;
            GroupBies = groupBies;
            Name = name;
            Search = search;
        }
    }
}
