// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Outputs
{

    [OutputType]
    public sealed class DashboardWidgetTimeseriesDefinitionRequestQueryApmResourceStatsQuery
    {
        /// <summary>
        /// The source organization UUID for cross organization queries. Feature in Private Beta.
        /// </summary>
        public readonly string? CrossOrgUuids;
        /// <summary>
        /// The data source for APM Resource Stats queries. Valid values are `ApmResourceStats`.
        /// </summary>
        public readonly string DataSource;
        /// <summary>
        /// APM environment.
        /// </summary>
        public readonly string Env;
        /// <summary>
        /// Array of fields to group results by.
        /// </summary>
        public readonly ImmutableArray<string> GroupBies;
        /// <summary>
        /// The name of query for use in formulas.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Name of operation on service.
        /// </summary>
        public readonly string? OperationName;
        /// <summary>
        /// The name of the second primary tag used within APM; required when `PrimaryTagValue` is specified. See https://docs.datadoghq.com/tracing/guide/setting*primary*tags*to*scope/#add-a-second-primary-tag-in-datadog.
        /// </summary>
        public readonly string? PrimaryTagName;
        /// <summary>
        /// Filter APM data by the second primary tag. `PrimaryTagName` must also be specified.
        /// </summary>
        public readonly string? PrimaryTagValue;
        /// <summary>
        /// APM resource.
        /// </summary>
        public readonly string? ResourceName;
        /// <summary>
        /// APM service.
        /// </summary>
        public readonly string Service;
        /// <summary>
        /// APM statistic. Valid values are `Errors`, `ErrorRate`, `Hits`, `LatencyAvg`, `LatencyDistribution`, `LatencyMax`, `LatencyP50`, `LatencyP75`, `LatencyP90`, `LatencyP95`, `LatencyP99`.
        /// </summary>
        public readonly string Stat;

        [OutputConstructor]
        private DashboardWidgetTimeseriesDefinitionRequestQueryApmResourceStatsQuery(
            string? crossOrgUuids,

            string dataSource,

            string env,

            ImmutableArray<string> groupBies,

            string name,

            string? operationName,

            string? primaryTagName,

            string? primaryTagValue,

            string? resourceName,

            string service,

            string stat)
        {
            CrossOrgUuids = crossOrgUuids;
            DataSource = dataSource;
            Env = env;
            GroupBies = groupBies;
            Name = name;
            OperationName = operationName;
            PrimaryTagName = primaryTagName;
            PrimaryTagValue = primaryTagValue;
            ResourceName = resourceName;
            Service = service;
            Stat = stat;
        }
    }
}
