// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Outputs
{

    [OutputType]
    public sealed class LogsCustomPipelineProcessorPipelineProcessorCategoryProcessor
    {
        /// <summary>
        /// List of filters to match or exclude a log with their corresponding name to assign a custom value to the log.
        /// </summary>
        public readonly ImmutableArray<Outputs.LogsCustomPipelineProcessorPipelineProcessorCategoryProcessorCategory> Categories;
        /// <summary>
        /// If the processor is enabled or not.
        /// </summary>
        public readonly bool? IsEnabled;
        /// <summary>
        /// Name of the category
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// Name of the target attribute whose value is defined by the matching category.
        /// </summary>
        public readonly string Target;

        [OutputConstructor]
        private LogsCustomPipelineProcessorPipelineProcessorCategoryProcessor(
            ImmutableArray<Outputs.LogsCustomPipelineProcessorPipelineProcessorCategoryProcessorCategory> categories,

            bool? isEnabled,

            string? name,

            string target)
        {
            Categories = categories;
            IsEnabled = isEnabled;
            Name = name;
            Target = target;
        }
    }
}
