// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Outputs
{

    [OutputType]
    public sealed class ObservabilityPipelineConfigDestinations
    {
        /// <summary>
        /// The `amazon_opensearch` destination writes logs to Amazon OpenSearch.
        /// </summary>
        public readonly ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsAmazonOpensearch> AmazonOpensearches;
        /// <summary>
        /// The `amazon_s3` destination sends your logs in Datadog-rehydratable format to an Amazon S3 bucket for archiving.
        /// </summary>
        public readonly ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsAmazonS3> AmazonS3s;
        /// <summary>
        /// The `amazon_security_lake` destination sends your logs to Amazon Security Lake.
        /// </summary>
        public readonly ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsAmazonSecurityLake> AmazonSecurityLakes;
        /// <summary>
        /// The `azure_storage` destination forwards logs to an Azure Blob Storage container.
        /// </summary>
        public readonly ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsAzureStorage> AzureStorages;
        /// <summary>
        /// The `crowdstrike_next_gen_siem` destination forwards logs to CrowdStrike Next Gen SIEM.
        /// </summary>
        public readonly ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsCrowdstrikeNextGenSiem> CrowdstrikeNextGenSiems;
        /// <summary>
        /// The `datadog_logs` destination forwards logs to Datadog Log Management.
        /// </summary>
        public readonly ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsDatadogLog> DatadogLogs;
        /// <summary>
        /// The `elasticsearch` destination writes logs to an Elasticsearch cluster.
        /// </summary>
        public readonly ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsElasticsearch> Elasticsearches;
        /// <summary>
        /// The `google_chronicle` destination sends logs to Google Chronicle.
        /// </summary>
        public readonly ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsGoogleChronicle> GoogleChronicles;
        /// <summary>
        /// The `google_cloud_storage` destination stores logs in a Google Cloud Storage (GCS) bucket.
        /// </summary>
        public readonly ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsGoogleCloudStorage> GoogleCloudStorages;
        /// <summary>
        /// The `google_pubsub` destination publishes logs to a Google Cloud Pub/Sub topic.
        /// </summary>
        public readonly ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsGooglePubsub> GooglePubsubs;
        /// <summary>
        /// The `microsoft_sentinel` destination forwards logs to Microsoft Sentinel.
        /// </summary>
        public readonly ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsMicrosoftSentinel> MicrosoftSentinels;
        /// <summary>
        /// The `new_relic` destination sends logs to the New Relic platform.
        /// </summary>
        public readonly ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsNewRelic> NewRelics;
        /// <summary>
        /// The `opensearch` destination writes logs to an OpenSearch cluster.
        /// </summary>
        public readonly ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsOpensearch> Opensearches;
        /// <summary>
        /// The `rsyslog` destination forwards logs to an external `rsyslog` server over TCP or UDP using the syslog protocol.
        /// </summary>
        public readonly ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsRsyslog> Rsyslogs;
        /// <summary>
        /// The `sentinel_one` destination sends logs to SentinelOne.
        /// </summary>
        public readonly ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsSentinelOne> SentinelOnes;
        /// <summary>
        /// The `socket` destination sends logs over TCP or UDP to a remote server.
        /// </summary>
        public readonly ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsSocket> Sockets;
        /// <summary>
        /// The `splunk_hec` destination forwards logs to Splunk using the HTTP Event Collector (HEC).
        /// </summary>
        public readonly ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsSplunkHec> SplunkHecs;
        /// <summary>
        /// The `sumo_logic` destination forwards logs to Sumo Logic.
        /// </summary>
        public readonly ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsSumoLogic> SumoLogics;
        /// <summary>
        /// The `syslog_ng` destination forwards logs to an external `syslog-ng` server over TCP or UDP using the syslog protocol.
        /// </summary>
        public readonly ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsSyslogNg> SyslogNgs;

        [OutputConstructor]
        private ObservabilityPipelineConfigDestinations(
            ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsAmazonOpensearch> amazonOpensearches,

            ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsAmazonS3> amazonS3s,

            ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsAmazonSecurityLake> amazonSecurityLakes,

            ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsAzureStorage> azureStorages,

            ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsCrowdstrikeNextGenSiem> crowdstrikeNextGenSiems,

            ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsDatadogLog> datadogLogs,

            ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsElasticsearch> elasticsearches,

            ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsGoogleChronicle> googleChronicles,

            ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsGoogleCloudStorage> googleCloudStorages,

            ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsGooglePubsub> googlePubsubs,

            ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsMicrosoftSentinel> microsoftSentinels,

            ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsNewRelic> newRelics,

            ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsOpensearch> opensearches,

            ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsRsyslog> rsyslogs,

            ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsSentinelOne> sentinelOnes,

            ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsSocket> sockets,

            ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsSplunkHec> splunkHecs,

            ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsSumoLogic> sumoLogics,

            ImmutableArray<Outputs.ObservabilityPipelineConfigDestinationsSyslogNg> syslogNgs)
        {
            AmazonOpensearches = amazonOpensearches;
            AmazonS3s = amazonS3s;
            AmazonSecurityLakes = amazonSecurityLakes;
            AzureStorages = azureStorages;
            CrowdstrikeNextGenSiems = crowdstrikeNextGenSiems;
            DatadogLogs = datadogLogs;
            Elasticsearches = elasticsearches;
            GoogleChronicles = googleChronicles;
            GoogleCloudStorages = googleCloudStorages;
            GooglePubsubs = googlePubsubs;
            MicrosoftSentinels = microsoftSentinels;
            NewRelics = newRelics;
            Opensearches = opensearches;
            Rsyslogs = rsyslogs;
            SentinelOnes = sentinelOnes;
            Sockets = sockets;
            SplunkHecs = splunkHecs;
            SumoLogics = sumoLogics;
            SyslogNgs = syslogNgs;
        }
    }
}
