// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Outputs
{

    [OutputType]
    public sealed class ObservabilityPipelineConfigDestinationKafkaSasl
    {
        /// <summary>
        /// SASL authentication mechanism. Valid values are `PLAIN`, `SCRAM-SHA-256`, `SCRAM-SHA-512`.
        /// </summary>
        public readonly string Mechanism;
        /// <summary>
        /// Name of the environment variable or secret that holds the SASL password.
        /// </summary>
        public readonly string? PasswordKey;
        /// <summary>
        /// Name of the environment variable or secret that holds the SASL username.
        /// </summary>
        public readonly string? UsernameKey;

        [OutputConstructor]
        private ObservabilityPipelineConfigDestinationKafkaSasl(
            string mechanism,

            string? passwordKey,

            string? usernameKey)
        {
            Mechanism = mechanism;
            PasswordKey = passwordKey;
            UsernameKey = usernameKey;
        }
    }
}
