// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Outputs
{

    [OutputType]
    public sealed class PowerpackV2WidgetWildcardDefinitionRequestTimeseriesRequestQueryProductAnalyticsExtendedQuery
    {
        /// <summary>
        /// Product Analytics audience filters.
        /// </summary>
        public readonly Outputs.PowerpackV2WidgetWildcardDefinitionRequestTimeseriesRequestQueryProductAnalyticsExtendedQueryAudienceFilters? AudienceFilters;
        /// <summary>
        /// Compute configuration for the Product Analytics Extended query.
        /// </summary>
        public readonly Outputs.PowerpackV2WidgetWildcardDefinitionRequestTimeseriesRequestQueryProductAnalyticsExtendedQueryCompute Compute;
        /// <summary>
        /// Data source for Product Analytics Extended queries. Valid values are `ProductAnalyticsExtended`.
        /// </summary>
        public readonly string DataSource;
        /// <summary>
        /// Group by configuration for the Product Analytics Extended query.
        /// </summary>
        public readonly ImmutableArray<Outputs.PowerpackV2WidgetWildcardDefinitionRequestTimeseriesRequestQueryProductAnalyticsExtendedQueryGroupBy> GroupBies;
        /// <summary>
        /// Event indexes to query. Use `*` to query all indexes.
        /// </summary>
        public readonly ImmutableArray<string> Indexes;
        /// <summary>
        /// Name of the query for use in formulas.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Base Product Analytics event query.
        /// </summary>
        public readonly Outputs.PowerpackV2WidgetWildcardDefinitionRequestTimeseriesRequestQueryProductAnalyticsExtendedQueryQuery Query;

        [OutputConstructor]
        private PowerpackV2WidgetWildcardDefinitionRequestTimeseriesRequestQueryProductAnalyticsExtendedQuery(
            Outputs.PowerpackV2WidgetWildcardDefinitionRequestTimeseriesRequestQueryProductAnalyticsExtendedQueryAudienceFilters? audienceFilters,

            Outputs.PowerpackV2WidgetWildcardDefinitionRequestTimeseriesRequestQueryProductAnalyticsExtendedQueryCompute compute,

            string dataSource,

            ImmutableArray<Outputs.PowerpackV2WidgetWildcardDefinitionRequestTimeseriesRequestQueryProductAnalyticsExtendedQueryGroupBy> groupBies,

            ImmutableArray<string> indexes,

            string name,

            Outputs.PowerpackV2WidgetWildcardDefinitionRequestTimeseriesRequestQueryProductAnalyticsExtendedQueryQuery query)
        {
            AudienceFilters = audienceFilters;
            Compute = compute;
            DataSource = dataSource;
            GroupBies = groupBies;
            Indexes = indexes;
            Name = name;
            Query = query;
        }
    }
}
