// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Outputs
{

    [OutputType]
    public sealed class PowerpackV2WidgetGroupDefinitionWidgetQueryValueDefinitionRequestQueryUserJourneyQuerySearch
    {
        /// <summary>
        /// Expression describing the journey between nodes.
        /// </summary>
        public readonly string Expression;
        /// <summary>
        /// Filters for the user journey search.
        /// </summary>
        public readonly Outputs.PowerpackV2WidgetGroupDefinitionWidgetQueryValueDefinitionRequestQueryUserJourneyQuerySearchFilters? Filters;
        /// <summary>
        /// Join keys for the user journey query.
        /// </summary>
        public readonly Outputs.PowerpackV2WidgetGroupDefinitionWidgetQueryValueDefinitionRequestQueryUserJourneyQuerySearchJoinKeys? JoinKeys;
        /// <summary>
        /// JSON object mapping journey node names to Product Analytics base queries.
        /// </summary>
        public readonly string NodeObjects;
        /// <summary>
        /// JSON object mapping journey step names to display aliases.
        /// </summary>
        public readonly string? StepAliases;

        [OutputConstructor]
        private PowerpackV2WidgetGroupDefinitionWidgetQueryValueDefinitionRequestQueryUserJourneyQuerySearch(
            string expression,

            Outputs.PowerpackV2WidgetGroupDefinitionWidgetQueryValueDefinitionRequestQueryUserJourneyQuerySearchFilters? filters,

            Outputs.PowerpackV2WidgetGroupDefinitionWidgetQueryValueDefinitionRequestQueryUserJourneyQuerySearchJoinKeys? joinKeys,

            string nodeObjects,

            string? stepAliases)
        {
            Expression = expression;
            Filters = filters;
            JoinKeys = joinKeys;
            NodeObjects = nodeObjects;
            StepAliases = stepAliases;
        }
    }
}
