// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Outputs
{

    [OutputType]
    public sealed class SyntheticsTestStep
    {
        public readonly bool? AllowFailure;
        public readonly string Name;
        public readonly string Params;
        public readonly int? Timeout;
        public readonly string Type;

        [OutputConstructor]
        private SyntheticsTestStep(
            bool? allowFailure,

            string name,

            string @params,

            int? timeout,

            string type)
        {
            AllowFailure = allowFailure;
            Name = name;
            Params = @params;
            Timeout = timeout;
            Type = type;
        }
    }
}
