// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DashboardWidgetGroupDefinitionWidgetHeatmapDefinitionEventArgs extends com.pulumi.resources.ResourceArgs {

    public static final DashboardWidgetGroupDefinitionWidgetHeatmapDefinitionEventArgs Empty = new DashboardWidgetGroupDefinitionWidgetHeatmapDefinitionEventArgs();

    /**
     * The metric query to use for this widget.
     * 
     */
    @Import(name="q", required=true)
    private Output<String> q;

    /**
     * @return The metric query to use for this widget.
     * 
     */
    public Output<String> q() {
        return this.q;
    }

    /**
     * The execution method for multi-value filters, options: `and` or `or`.
     * 
     */
    @Import(name="tagsExecution")
    private @Nullable Output<String> tagsExecution;

    /**
     * @return The execution method for multi-value filters, options: `and` or `or`.
     * 
     */
    public Optional<Output<String>> tagsExecution() {
        return Optional.ofNullable(this.tagsExecution);
    }

    private DashboardWidgetGroupDefinitionWidgetHeatmapDefinitionEventArgs() {}

    private DashboardWidgetGroupDefinitionWidgetHeatmapDefinitionEventArgs(DashboardWidgetGroupDefinitionWidgetHeatmapDefinitionEventArgs $) {
        this.q = $.q;
        this.tagsExecution = $.tagsExecution;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DashboardWidgetGroupDefinitionWidgetHeatmapDefinitionEventArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DashboardWidgetGroupDefinitionWidgetHeatmapDefinitionEventArgs $;

        public Builder() {
            $ = new DashboardWidgetGroupDefinitionWidgetHeatmapDefinitionEventArgs();
        }

        public Builder(DashboardWidgetGroupDefinitionWidgetHeatmapDefinitionEventArgs defaults) {
            $ = new DashboardWidgetGroupDefinitionWidgetHeatmapDefinitionEventArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param q The metric query to use for this widget.
         * 
         * @return builder
         * 
         */
        public Builder q(Output<String> q) {
            $.q = q;
            return this;
        }

        /**
         * @param q The metric query to use for this widget.
         * 
         * @return builder
         * 
         */
        public Builder q(String q) {
            return q(Output.of(q));
        }

        /**
         * @param tagsExecution The execution method for multi-value filters, options: `and` or `or`.
         * 
         * @return builder
         * 
         */
        public Builder tagsExecution(@Nullable Output<String> tagsExecution) {
            $.tagsExecution = tagsExecution;
            return this;
        }

        /**
         * @param tagsExecution The execution method for multi-value filters, options: `and` or `or`.
         * 
         * @return builder
         * 
         */
        public Builder tagsExecution(String tagsExecution) {
            return tagsExecution(Output.of(tagsExecution));
        }

        public DashboardWidgetGroupDefinitionWidgetHeatmapDefinitionEventArgs build() {
            if ($.q == null) {
                throw new MissingRequiredPropertyException("DashboardWidgetGroupDefinitionWidgetHeatmapDefinitionEventArgs", "q");
            }
            return $;
        }
    }

}
