// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.datadog.inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestProjectionDimensionNumberFormatArgs;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestProjectionDimensionArgs extends com.pulumi.resources.ResourceArgs {

    public static final DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestProjectionDimensionArgs Empty = new DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestProjectionDimensionArgs();

    /**
     * Alias used to label the column instead of its name.
     * 
     */
    @Import(name="alias")
    private @Nullable Output<String> alias;

    /**
     * @return Alias used to label the column instead of its name.
     * 
     */
    public Optional<Output<String>> alias() {
        return Optional.ofNullable(this.alias);
    }

    /**
     * Source column name from the dataset.
     * 
     */
    @Import(name="column", required=true)
    private Output<String> column;

    /**
     * @return Source column name from the dataset.
     * 
     */
    public Output<String> column() {
        return this.column;
    }

    /**
     * Visual dimension driven by the dataset column. Valid values are `node`, `fill`, `size`, `group`.
     * 
     */
    @Import(name="dimension", required=true)
    private Output<String> dimension;

    /**
     * @return Visual dimension driven by the dataset column. Valid values are `node`, `fill`, `size`, `group`.
     * 
     */
    public Output<String> dimension() {
        return this.dimension;
    }

    /**
     * Number formatting options for the projected column.
     * 
     */
    @Import(name="numberFormat")
    private @Nullable Output<DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestProjectionDimensionNumberFormatArgs> numberFormat;

    /**
     * @return Number formatting options for the projected column.
     * 
     */
    public Optional<Output<DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestProjectionDimensionNumberFormatArgs>> numberFormat() {
        return Optional.ofNullable(this.numberFormat);
    }

    private DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestProjectionDimensionArgs() {}

    private DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestProjectionDimensionArgs(DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestProjectionDimensionArgs $) {
        this.alias = $.alias;
        this.column = $.column;
        this.dimension = $.dimension;
        this.numberFormat = $.numberFormat;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestProjectionDimensionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestProjectionDimensionArgs $;

        public Builder() {
            $ = new DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestProjectionDimensionArgs();
        }

        public Builder(DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestProjectionDimensionArgs defaults) {
            $ = new DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestProjectionDimensionArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param alias Alias used to label the column instead of its name.
         * 
         * @return builder
         * 
         */
        public Builder alias(@Nullable Output<String> alias) {
            $.alias = alias;
            return this;
        }

        /**
         * @param alias Alias used to label the column instead of its name.
         * 
         * @return builder
         * 
         */
        public Builder alias(String alias) {
            return alias(Output.of(alias));
        }

        /**
         * @param column Source column name from the dataset.
         * 
         * @return builder
         * 
         */
        public Builder column(Output<String> column) {
            $.column = column;
            return this;
        }

        /**
         * @param column Source column name from the dataset.
         * 
         * @return builder
         * 
         */
        public Builder column(String column) {
            return column(Output.of(column));
        }

        /**
         * @param dimension Visual dimension driven by the dataset column. Valid values are `node`, `fill`, `size`, `group`.
         * 
         * @return builder
         * 
         */
        public Builder dimension(Output<String> dimension) {
            $.dimension = dimension;
            return this;
        }

        /**
         * @param dimension Visual dimension driven by the dataset column. Valid values are `node`, `fill`, `size`, `group`.
         * 
         * @return builder
         * 
         */
        public Builder dimension(String dimension) {
            return dimension(Output.of(dimension));
        }

        /**
         * @param numberFormat Number formatting options for the projected column.
         * 
         * @return builder
         * 
         */
        public Builder numberFormat(@Nullable Output<DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestProjectionDimensionNumberFormatArgs> numberFormat) {
            $.numberFormat = numberFormat;
            return this;
        }

        /**
         * @param numberFormat Number formatting options for the projected column.
         * 
         * @return builder
         * 
         */
        public Builder numberFormat(DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestProjectionDimensionNumberFormatArgs numberFormat) {
            return numberFormat(Output.of(numberFormat));
        }

        public DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestProjectionDimensionArgs build() {
            if ($.column == null) {
                throw new MissingRequiredPropertyException("DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestProjectionDimensionArgs", "column");
            }
            if ($.dimension == null) {
                throw new MissingRequiredPropertyException("DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestProjectionDimensionArgs", "dimension");
            }
            return $;
        }
    }

}
