// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.datadog.inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryAudienceFiltersArgs;
import com.pulumi.datadog.inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryComputeArgs;
import com.pulumi.datadog.inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryGroupByArgs;
import com.pulumi.datadog.inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryQueryArgs;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryArgs extends com.pulumi.resources.ResourceArgs {

    public static final DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryArgs Empty = new DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryArgs();

    /**
     * Product Analytics audience filters.
     * 
     */
    @Import(name="audienceFilters")
    private @Nullable Output<DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryAudienceFiltersArgs> audienceFilters;

    /**
     * @return Product Analytics audience filters.
     * 
     */
    public Optional<Output<DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryAudienceFiltersArgs>> audienceFilters() {
        return Optional.ofNullable(this.audienceFilters);
    }

    /**
     * Compute configuration for the Product Analytics Extended query.
     * 
     */
    @Import(name="compute", required=true)
    private Output<DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryComputeArgs> compute;

    /**
     * @return Compute configuration for the Product Analytics Extended query.
     * 
     */
    public Output<DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryComputeArgs> compute() {
        return this.compute;
    }

    /**
     * Data source for Product Analytics Extended queries. Valid values are `productAnalyticsExtended`.
     * 
     */
    @Import(name="dataSource", required=true)
    private Output<String> dataSource;

    /**
     * @return Data source for Product Analytics Extended queries. Valid values are `productAnalyticsExtended`.
     * 
     */
    public Output<String> dataSource() {
        return this.dataSource;
    }

    /**
     * Group by configuration for the Product Analytics Extended query.
     * 
     */
    @Import(name="groupBies")
    private @Nullable Output<List<DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryGroupByArgs>> groupBies;

    /**
     * @return Group by configuration for the Product Analytics Extended query.
     * 
     */
    public Optional<Output<List<DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryGroupByArgs>>> groupBies() {
        return Optional.ofNullable(this.groupBies);
    }

    /**
     * Event indexes to query. Use `*` to query all indexes.
     * 
     */
    @Import(name="indexes")
    private @Nullable Output<List<String>> indexes;

    /**
     * @return Event indexes to query. Use `*` to query all indexes.
     * 
     */
    public Optional<Output<List<String>>> indexes() {
        return Optional.ofNullable(this.indexes);
    }

    /**
     * Name of the query for use in formulas.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Name of the query for use in formulas.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * Base Product Analytics event query.
     * 
     */
    @Import(name="query", required=true)
    private Output<DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryQueryArgs> query;

    /**
     * @return Base Product Analytics event query.
     * 
     */
    public Output<DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryQueryArgs> query() {
        return this.query;
    }

    private DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryArgs() {}

    private DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryArgs(DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryArgs $) {
        this.audienceFilters = $.audienceFilters;
        this.compute = $.compute;
        this.dataSource = $.dataSource;
        this.groupBies = $.groupBies;
        this.indexes = $.indexes;
        this.name = $.name;
        this.query = $.query;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryArgs $;

        public Builder() {
            $ = new DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryArgs();
        }

        public Builder(DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryArgs defaults) {
            $ = new DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param audienceFilters Product Analytics audience filters.
         * 
         * @return builder
         * 
         */
        public Builder audienceFilters(@Nullable Output<DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryAudienceFiltersArgs> audienceFilters) {
            $.audienceFilters = audienceFilters;
            return this;
        }

        /**
         * @param audienceFilters Product Analytics audience filters.
         * 
         * @return builder
         * 
         */
        public Builder audienceFilters(DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryAudienceFiltersArgs audienceFilters) {
            return audienceFilters(Output.of(audienceFilters));
        }

        /**
         * @param compute Compute configuration for the Product Analytics Extended query.
         * 
         * @return builder
         * 
         */
        public Builder compute(Output<DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryComputeArgs> compute) {
            $.compute = compute;
            return this;
        }

        /**
         * @param compute Compute configuration for the Product Analytics Extended query.
         * 
         * @return builder
         * 
         */
        public Builder compute(DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryComputeArgs compute) {
            return compute(Output.of(compute));
        }

        /**
         * @param dataSource Data source for Product Analytics Extended queries. Valid values are `productAnalyticsExtended`.
         * 
         * @return builder
         * 
         */
        public Builder dataSource(Output<String> dataSource) {
            $.dataSource = dataSource;
            return this;
        }

        /**
         * @param dataSource Data source for Product Analytics Extended queries. Valid values are `productAnalyticsExtended`.
         * 
         * @return builder
         * 
         */
        public Builder dataSource(String dataSource) {
            return dataSource(Output.of(dataSource));
        }

        /**
         * @param groupBies Group by configuration for the Product Analytics Extended query.
         * 
         * @return builder
         * 
         */
        public Builder groupBies(@Nullable Output<List<DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryGroupByArgs>> groupBies) {
            $.groupBies = groupBies;
            return this;
        }

        /**
         * @param groupBies Group by configuration for the Product Analytics Extended query.
         * 
         * @return builder
         * 
         */
        public Builder groupBies(List<DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryGroupByArgs> groupBies) {
            return groupBies(Output.of(groupBies));
        }

        /**
         * @param groupBies Group by configuration for the Product Analytics Extended query.
         * 
         * @return builder
         * 
         */
        public Builder groupBies(DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryGroupByArgs... groupBies) {
            return groupBies(List.of(groupBies));
        }

        /**
         * @param indexes Event indexes to query. Use `*` to query all indexes.
         * 
         * @return builder
         * 
         */
        public Builder indexes(@Nullable Output<List<String>> indexes) {
            $.indexes = indexes;
            return this;
        }

        /**
         * @param indexes Event indexes to query. Use `*` to query all indexes.
         * 
         * @return builder
         * 
         */
        public Builder indexes(List<String> indexes) {
            return indexes(Output.of(indexes));
        }

        /**
         * @param indexes Event indexes to query. Use `*` to query all indexes.
         * 
         * @return builder
         * 
         */
        public Builder indexes(String... indexes) {
            return indexes(List.of(indexes));
        }

        /**
         * @param name Name of the query for use in formulas.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Name of the query for use in formulas.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param query Base Product Analytics event query.
         * 
         * @return builder
         * 
         */
        public Builder query(Output<DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryQueryArgs> query) {
            $.query = query;
            return this;
        }

        /**
         * @param query Base Product Analytics event query.
         * 
         * @return builder
         * 
         */
        public Builder query(DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryQueryArgs query) {
            return query(Output.of(query));
        }

        public DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryArgs build() {
            if ($.compute == null) {
                throw new MissingRequiredPropertyException("DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryArgs", "compute");
            }
            if ($.dataSource == null) {
                throw new MissingRequiredPropertyException("DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryArgs", "dataSource");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryArgs", "name");
            }
            if ($.query == null) {
                throw new MissingRequiredPropertyException("DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryProductAnalyticsExtendedQueryArgs", "query");
            }
            return $;
        }
    }

}
