// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class DashboardV2WidgetGroupDefinitionWidgetTreemapDefinitionRequestFormulaNumberFormatUnitScaleArgs extends com.pulumi.resources.ResourceArgs {

    public static final DashboardV2WidgetGroupDefinitionWidgetTreemapDefinitionRequestFormulaNumberFormatUnitScaleArgs Empty = new DashboardV2WidgetGroupDefinitionWidgetTreemapDefinitionRequestFormulaNumberFormatUnitScaleArgs();

    /**
     * The name of the unit.
     * 
     */
    @Import(name="unitName", required=true)
    private Output<String> unitName;

    /**
     * @return The name of the unit.
     * 
     */
    public Output<String> unitName() {
        return this.unitName;
    }

    private DashboardV2WidgetGroupDefinitionWidgetTreemapDefinitionRequestFormulaNumberFormatUnitScaleArgs() {}

    private DashboardV2WidgetGroupDefinitionWidgetTreemapDefinitionRequestFormulaNumberFormatUnitScaleArgs(DashboardV2WidgetGroupDefinitionWidgetTreemapDefinitionRequestFormulaNumberFormatUnitScaleArgs $) {
        this.unitName = $.unitName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DashboardV2WidgetGroupDefinitionWidgetTreemapDefinitionRequestFormulaNumberFormatUnitScaleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DashboardV2WidgetGroupDefinitionWidgetTreemapDefinitionRequestFormulaNumberFormatUnitScaleArgs $;

        public Builder() {
            $ = new DashboardV2WidgetGroupDefinitionWidgetTreemapDefinitionRequestFormulaNumberFormatUnitScaleArgs();
        }

        public Builder(DashboardV2WidgetGroupDefinitionWidgetTreemapDefinitionRequestFormulaNumberFormatUnitScaleArgs defaults) {
            $ = new DashboardV2WidgetGroupDefinitionWidgetTreemapDefinitionRequestFormulaNumberFormatUnitScaleArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param unitName The name of the unit.
         * 
         * @return builder
         * 
         */
        public Builder unitName(Output<String> unitName) {
            $.unitName = unitName;
            return this;
        }

        /**
         * @param unitName The name of the unit.
         * 
         * @return builder
         * 
         */
        public Builder unitName(String unitName) {
            return unitName(Output.of(unitName));
        }

        public DashboardV2WidgetGroupDefinitionWidgetTreemapDefinitionRequestFormulaNumberFormatUnitScaleArgs build() {
            if ($.unitName == null) {
                throw new MissingRequiredPropertyException("DashboardV2WidgetGroupDefinitionWidgetTreemapDefinitionRequestFormulaNumberFormatUnitScaleArgs", "unitName");
            }
            return $;
        }
    }

}
