// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionScatterplotDefinitionRequestScatterplotTableQueryRetentionQueryComputeArgs extends com.pulumi.resources.ResourceArgs {

    public static final DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionScatterplotDefinitionRequestScatterplotTableQueryRetentionQueryComputeArgs Empty = new DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionScatterplotDefinitionRequestScatterplotTableQueryRetentionQueryComputeArgs();

    /**
     * Aggregation for the retention query, including standard event aggregations and `pcNN` percentiles.
     * 
     */
    @Import(name="aggregation", required=true)
    private Output<String> aggregation;

    /**
     * @return Aggregation for the retention query, including standard event aggregations and `pcNN` percentiles.
     * 
     */
    public Output<String> aggregation() {
        return this.aggregation;
    }

    /**
     * Metric for the retention computation. Valid values are `__dd.retention`, `__dd.retention_rate`.
     * 
     */
    @Import(name="metric", required=true)
    private Output<String> metric;

    /**
     * @return Metric for the retention computation. Valid values are `__dd.retention`, `__dd.retention_rate`.
     * 
     */
    public Output<String> metric() {
        return this.metric;
    }

    private DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionScatterplotDefinitionRequestScatterplotTableQueryRetentionQueryComputeArgs() {}

    private DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionScatterplotDefinitionRequestScatterplotTableQueryRetentionQueryComputeArgs(DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionScatterplotDefinitionRequestScatterplotTableQueryRetentionQueryComputeArgs $) {
        this.aggregation = $.aggregation;
        this.metric = $.metric;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionScatterplotDefinitionRequestScatterplotTableQueryRetentionQueryComputeArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionScatterplotDefinitionRequestScatterplotTableQueryRetentionQueryComputeArgs $;

        public Builder() {
            $ = new DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionScatterplotDefinitionRequestScatterplotTableQueryRetentionQueryComputeArgs();
        }

        public Builder(DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionScatterplotDefinitionRequestScatterplotTableQueryRetentionQueryComputeArgs defaults) {
            $ = new DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionScatterplotDefinitionRequestScatterplotTableQueryRetentionQueryComputeArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param aggregation Aggregation for the retention query, including standard event aggregations and `pcNN` percentiles.
         * 
         * @return builder
         * 
         */
        public Builder aggregation(Output<String> aggregation) {
            $.aggregation = aggregation;
            return this;
        }

        /**
         * @param aggregation Aggregation for the retention query, including standard event aggregations and `pcNN` percentiles.
         * 
         * @return builder
         * 
         */
        public Builder aggregation(String aggregation) {
            return aggregation(Output.of(aggregation));
        }

        /**
         * @param metric Metric for the retention computation. Valid values are `__dd.retention`, `__dd.retention_rate`.
         * 
         * @return builder
         * 
         */
        public Builder metric(Output<String> metric) {
            $.metric = metric;
            return this;
        }

        /**
         * @param metric Metric for the retention computation. Valid values are `__dd.retention`, `__dd.retention_rate`.
         * 
         * @return builder
         * 
         */
        public Builder metric(String metric) {
            return metric(Output.of(metric));
        }

        public DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionScatterplotDefinitionRequestScatterplotTableQueryRetentionQueryComputeArgs build() {
            if ($.aggregation == null) {
                throw new MissingRequiredPropertyException("DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionScatterplotDefinitionRequestScatterplotTableQueryRetentionQueryComputeArgs", "aggregation");
            }
            if ($.metric == null) {
                throw new MissingRequiredPropertyException("DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionScatterplotDefinitionRequestScatterplotTableQueryRetentionQueryComputeArgs", "metric");
            }
            return $;
        }
    }

}
