// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.datadog.inputs.DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryComputeQueryArgs;
import com.pulumi.datadog.inputs.DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryGroupByArgs;
import com.pulumi.datadog.inputs.DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryMultiComputeArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryArgs extends com.pulumi.resources.ResourceArgs {

    public static final DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryArgs Empty = new DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryArgs();

    @Import(name="computeQuery")
    private @Nullable Output<DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryComputeQueryArgs> computeQuery;

    public Optional<Output<DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryComputeQueryArgs>> computeQuery() {
        return Optional.ofNullable(this.computeQuery);
    }

    @Import(name="groupBies")
    private @Nullable Output<List<DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryGroupByArgs>> groupBies;

    public Optional<Output<List<DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryGroupByArgs>>> groupBies() {
        return Optional.ofNullable(this.groupBies);
    }

    @Import(name="index", required=true)
    private Output<String> index;

    public Output<String> index() {
        return this.index;
    }

    @Import(name="multiComputes")
    private @Nullable Output<List<DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryMultiComputeArgs>> multiComputes;

    public Optional<Output<List<DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryMultiComputeArgs>>> multiComputes() {
        return Optional.ofNullable(this.multiComputes);
    }

    @Import(name="searchQuery")
    private @Nullable Output<String> searchQuery;

    public Optional<Output<String>> searchQuery() {
        return Optional.ofNullable(this.searchQuery);
    }

    private DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryArgs() {}

    private DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryArgs(DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryArgs $) {
        this.computeQuery = $.computeQuery;
        this.groupBies = $.groupBies;
        this.index = $.index;
        this.multiComputes = $.multiComputes;
        this.searchQuery = $.searchQuery;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryArgs $;

        public Builder() {
            $ = new DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryArgs();
        }

        public Builder(DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryArgs defaults) {
            $ = new DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryArgs(Objects.requireNonNull(defaults));
        }

        public Builder computeQuery(@Nullable Output<DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryComputeQueryArgs> computeQuery) {
            $.computeQuery = computeQuery;
            return this;
        }

        public Builder computeQuery(DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryComputeQueryArgs computeQuery) {
            return computeQuery(Output.of(computeQuery));
        }

        public Builder groupBies(@Nullable Output<List<DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryGroupByArgs>> groupBies) {
            $.groupBies = groupBies;
            return this;
        }

        public Builder groupBies(List<DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryGroupByArgs> groupBies) {
            return groupBies(Output.of(groupBies));
        }

        public Builder groupBies(DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryGroupByArgs... groupBies) {
            return groupBies(List.of(groupBies));
        }

        public Builder index(Output<String> index) {
            $.index = index;
            return this;
        }

        public Builder index(String index) {
            return index(Output.of(index));
        }

        public Builder multiComputes(@Nullable Output<List<DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryMultiComputeArgs>> multiComputes) {
            $.multiComputes = multiComputes;
            return this;
        }

        public Builder multiComputes(List<DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryMultiComputeArgs> multiComputes) {
            return multiComputes(Output.of(multiComputes));
        }

        public Builder multiComputes(DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryMultiComputeArgs... multiComputes) {
            return multiComputes(List.of(multiComputes));
        }

        public Builder searchQuery(@Nullable Output<String> searchQuery) {
            $.searchQuery = searchQuery;
            return this;
        }

        public Builder searchQuery(String searchQuery) {
            return searchQuery(Output.of(searchQuery));
        }

        public DashboardWidgetGroupDefinitionWidgetSunburstDefinitionRequestApmQueryArgs build() {
            $.index = Objects.requireNonNull($.index, "expected parameter 'index' to be non-null");
            return $;
        }
    }

}
