// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;


public final class DashboardV2WidgetGroupDefinitionWidgetDistributionDefinitionTimeLiveArgs extends com.pulumi.resources.ResourceArgs {

    public static final DashboardV2WidgetGroupDefinitionWidgetDistributionDefinitionTimeLiveArgs Empty = new DashboardV2WidgetGroupDefinitionWidgetDistributionDefinitionTimeLiveArgs();

    /**
     * Unit of the time span. Valid values are `minute`, `hour`, `day`, `week`, `month`, `year`.
     * 
     */
    @Import(name="unit", required=true)
    private Output<String> unit;

    /**
     * @return Unit of the time span. Valid values are `minute`, `hour`, `day`, `week`, `month`, `year`.
     * 
     */
    public Output<String> unit() {
        return this.unit;
    }

    /**
     * Value of the time span.
     * 
     */
    @Import(name="value", required=true)
    private Output<Integer> value;

    /**
     * @return Value of the time span.
     * 
     */
    public Output<Integer> value() {
        return this.value;
    }

    private DashboardV2WidgetGroupDefinitionWidgetDistributionDefinitionTimeLiveArgs() {}

    private DashboardV2WidgetGroupDefinitionWidgetDistributionDefinitionTimeLiveArgs(DashboardV2WidgetGroupDefinitionWidgetDistributionDefinitionTimeLiveArgs $) {
        this.unit = $.unit;
        this.value = $.value;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DashboardV2WidgetGroupDefinitionWidgetDistributionDefinitionTimeLiveArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DashboardV2WidgetGroupDefinitionWidgetDistributionDefinitionTimeLiveArgs $;

        public Builder() {
            $ = new DashboardV2WidgetGroupDefinitionWidgetDistributionDefinitionTimeLiveArgs();
        }

        public Builder(DashboardV2WidgetGroupDefinitionWidgetDistributionDefinitionTimeLiveArgs defaults) {
            $ = new DashboardV2WidgetGroupDefinitionWidgetDistributionDefinitionTimeLiveArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param unit Unit of the time span. Valid values are `minute`, `hour`, `day`, `week`, `month`, `year`.
         * 
         * @return builder
         * 
         */
        public Builder unit(Output<String> unit) {
            $.unit = unit;
            return this;
        }

        /**
         * @param unit Unit of the time span. Valid values are `minute`, `hour`, `day`, `week`, `month`, `year`.
         * 
         * @return builder
         * 
         */
        public Builder unit(String unit) {
            return unit(Output.of(unit));
        }

        /**
         * @param value Value of the time span.
         * 
         * @return builder
         * 
         */
        public Builder value(Output<Integer> value) {
            $.value = value;
            return this;
        }

        /**
         * @param value Value of the time span.
         * 
         * @return builder
         * 
         */
        public Builder value(Integer value) {
            return value(Output.of(value));
        }

        public DashboardV2WidgetGroupDefinitionWidgetDistributionDefinitionTimeLiveArgs build() {
            if ($.unit == null) {
                throw new MissingRequiredPropertyException("DashboardV2WidgetGroupDefinitionWidgetDistributionDefinitionTimeLiveArgs", "unit");
            }
            if ($.value == null) {
                throw new MissingRequiredPropertyException("DashboardV2WidgetGroupDefinitionWidgetDistributionDefinitionTimeLiveArgs", "value");
            }
            return $;
        }
    }

}
