// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class DashboardV2WidgetDistributionDefinitionRequestHistogramQueryEventQuerySearchArgs extends com.pulumi.resources.ResourceArgs {

    public static final DashboardV2WidgetDistributionDefinitionRequestHistogramQueryEventQuerySearchArgs Empty = new DashboardV2WidgetDistributionDefinitionRequestHistogramQueryEventQuerySearchArgs();

    /**
     * The events search string.
     * 
     */
    @Import(name="query", required=true)
    private Output<String> query;

    /**
     * @return The events search string.
     * 
     */
    public Output<String> query() {
        return this.query;
    }

    private DashboardV2WidgetDistributionDefinitionRequestHistogramQueryEventQuerySearchArgs() {}

    private DashboardV2WidgetDistributionDefinitionRequestHistogramQueryEventQuerySearchArgs(DashboardV2WidgetDistributionDefinitionRequestHistogramQueryEventQuerySearchArgs $) {
        this.query = $.query;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DashboardV2WidgetDistributionDefinitionRequestHistogramQueryEventQuerySearchArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DashboardV2WidgetDistributionDefinitionRequestHistogramQueryEventQuerySearchArgs $;

        public Builder() {
            $ = new DashboardV2WidgetDistributionDefinitionRequestHistogramQueryEventQuerySearchArgs();
        }

        public Builder(DashboardV2WidgetDistributionDefinitionRequestHistogramQueryEventQuerySearchArgs defaults) {
            $ = new DashboardV2WidgetDistributionDefinitionRequestHistogramQueryEventQuerySearchArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param query The events search string.
         * 
         * @return builder
         * 
         */
        public Builder query(Output<String> query) {
            $.query = query;
            return this;
        }

        /**
         * @param query The events search string.
         * 
         * @return builder
         * 
         */
        public Builder query(String query) {
            return query(Output.of(query));
        }

        public DashboardV2WidgetDistributionDefinitionRequestHistogramQueryEventQuerySearchArgs build() {
            if ($.query == null) {
                throw new MissingRequiredPropertyException("DashboardV2WidgetDistributionDefinitionRequestHistogramQueryEventQuerySearchArgs", "query");
            }
            return $;
        }
    }

}
