// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.datadog.inputs.DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQuerySearchArgs;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQueryArgs extends com.pulumi.resources.ResourceArgs {

    public static final DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQueryArgs Empty = new DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQueryArgs();

    /**
     * Data source for the Product Analytics event query. Valid values are `productAnalytics`.
     * 
     */
    @Import(name="dataSource", required=true)
    private Output<String> dataSource;

    /**
     * @return Data source for the Product Analytics event query. Valid values are `productAnalytics`.
     * 
     */
    public Output<String> dataSource() {
        return this.dataSource;
    }

    /**
     * Search configuration for the Product Analytics event query.
     * 
     */
    @Import(name="search", required=true)
    private Output<DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQuerySearchArgs> search;

    /**
     * @return Search configuration for the Product Analytics event query.
     * 
     */
    public Output<DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQuerySearchArgs> search() {
        return this.search;
    }

    private DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQueryArgs() {}

    private DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQueryArgs(DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQueryArgs $) {
        this.dataSource = $.dataSource;
        this.search = $.search;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQueryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQueryArgs $;

        public Builder() {
            $ = new DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQueryArgs();
        }

        public Builder(DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQueryArgs defaults) {
            $ = new DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQueryArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param dataSource Data source for the Product Analytics event query. Valid values are `productAnalytics`.
         * 
         * @return builder
         * 
         */
        public Builder dataSource(Output<String> dataSource) {
            $.dataSource = dataSource;
            return this;
        }

        /**
         * @param dataSource Data source for the Product Analytics event query. Valid values are `productAnalytics`.
         * 
         * @return builder
         * 
         */
        public Builder dataSource(String dataSource) {
            return dataSource(Output.of(dataSource));
        }

        /**
         * @param search Search configuration for the Product Analytics event query.
         * 
         * @return builder
         * 
         */
        public Builder search(Output<DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQuerySearchArgs> search) {
            $.search = search;
            return this;
        }

        /**
         * @param search Search configuration for the Product Analytics event query.
         * 
         * @return builder
         * 
         */
        public Builder search(DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQuerySearchArgs search) {
            return search(Output.of(search));
        }

        public DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQueryArgs build() {
            if ($.dataSource == null) {
                throw new MissingRequiredPropertyException("DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQueryArgs", "dataSource");
            }
            if ($.search == null) {
                throw new MissingRequiredPropertyException("DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQueryArgs", "search");
            }
            return $;
        }
    }

}
