// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetAppBuilderAppPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAppBuilderAppPlainArgs Empty = new GetAppBuilderAppPlainArgs();

    /**
     * ID for the App.
     * 
     */
    @Import(name="id", required=true)
    private String id;

    /**
     * @return ID for the App.
     * 
     */
    public String id() {
        return this.id;
    }

    private GetAppBuilderAppPlainArgs() {}

    private GetAppBuilderAppPlainArgs(GetAppBuilderAppPlainArgs $) {
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAppBuilderAppPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAppBuilderAppPlainArgs $;

        public Builder() {
            $ = new GetAppBuilderAppPlainArgs();
        }

        public Builder(GetAppBuilderAppPlainArgs defaults) {
            $ = new GetAppBuilderAppPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id ID for the App.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            $.id = id;
            return this;
        }

        public GetAppBuilderAppPlainArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetAppBuilderAppPlainArgs", "id");
            }
            return $;
        }
    }

}
