// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetRumRetentionFiltersPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetRumRetentionFiltersPlainArgs Empty = new GetRumRetentionFiltersPlainArgs();

    /**
     * RUM application ID.
     * 
     */
    @Import(name="applicationId", required=true)
    private String applicationId;

    /**
     * @return RUM application ID.
     * 
     */
    public String applicationId() {
        return this.applicationId;
    }

    private GetRumRetentionFiltersPlainArgs() {}

    private GetRumRetentionFiltersPlainArgs(GetRumRetentionFiltersPlainArgs $) {
        this.applicationId = $.applicationId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetRumRetentionFiltersPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetRumRetentionFiltersPlainArgs $;

        public Builder() {
            $ = new GetRumRetentionFiltersPlainArgs();
        }

        public Builder(GetRumRetentionFiltersPlainArgs defaults) {
            $ = new GetRumRetentionFiltersPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param applicationId RUM application ID.
         * 
         * @return builder
         * 
         */
        public Builder applicationId(String applicationId) {
            $.applicationId = applicationId;
            return this;
        }

        public GetRumRetentionFiltersPlainArgs build() {
            if ($.applicationId == null) {
                throw new MissingRequiredPropertyException("GetRumRetentionFiltersPlainArgs", "applicationId");
            }
            return $;
        }
    }

}
