// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;


public final class GetTagPipelineRulesetRuleMappingArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetTagPipelineRulesetRuleMappingArgs Empty = new GetTagPipelineRulesetRuleMappingArgs();

    /**
     * The destination key for the mapping.
     * 
     */
    @Import(name="destinationKey", required=true)
    private Output<String> destinationKey;

    /**
     * @return The destination key for the mapping.
     * 
     */
    public Output<String> destinationKey() {
        return this.destinationKey;
    }

    /**
     * Whether to apply the mapping only if the destination key doesn&#39;t exist.
     * 
     */
    @Import(name="ifNotExists", required=true)
    private Output<Boolean> ifNotExists;

    /**
     * @return Whether to apply the mapping only if the destination key doesn&#39;t exist.
     * 
     */
    public Output<Boolean> ifNotExists() {
        return this.ifNotExists;
    }

    /**
     * The source keys for the mapping.
     * 
     */
    @Import(name="sourceKeys", required=true)
    private Output<List<String>> sourceKeys;

    /**
     * @return The source keys for the mapping.
     * 
     */
    public Output<List<String>> sourceKeys() {
        return this.sourceKeys;
    }

    private GetTagPipelineRulesetRuleMappingArgs() {}

    private GetTagPipelineRulesetRuleMappingArgs(GetTagPipelineRulesetRuleMappingArgs $) {
        this.destinationKey = $.destinationKey;
        this.ifNotExists = $.ifNotExists;
        this.sourceKeys = $.sourceKeys;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetTagPipelineRulesetRuleMappingArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetTagPipelineRulesetRuleMappingArgs $;

        public Builder() {
            $ = new GetTagPipelineRulesetRuleMappingArgs();
        }

        public Builder(GetTagPipelineRulesetRuleMappingArgs defaults) {
            $ = new GetTagPipelineRulesetRuleMappingArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param destinationKey The destination key for the mapping.
         * 
         * @return builder
         * 
         */
        public Builder destinationKey(Output<String> destinationKey) {
            $.destinationKey = destinationKey;
            return this;
        }

        /**
         * @param destinationKey The destination key for the mapping.
         * 
         * @return builder
         * 
         */
        public Builder destinationKey(String destinationKey) {
            return destinationKey(Output.of(destinationKey));
        }

        /**
         * @param ifNotExists Whether to apply the mapping only if the destination key doesn&#39;t exist.
         * 
         * @return builder
         * 
         */
        public Builder ifNotExists(Output<Boolean> ifNotExists) {
            $.ifNotExists = ifNotExists;
            return this;
        }

        /**
         * @param ifNotExists Whether to apply the mapping only if the destination key doesn&#39;t exist.
         * 
         * @return builder
         * 
         */
        public Builder ifNotExists(Boolean ifNotExists) {
            return ifNotExists(Output.of(ifNotExists));
        }

        /**
         * @param sourceKeys The source keys for the mapping.
         * 
         * @return builder
         * 
         */
        public Builder sourceKeys(Output<List<String>> sourceKeys) {
            $.sourceKeys = sourceKeys;
            return this;
        }

        /**
         * @param sourceKeys The source keys for the mapping.
         * 
         * @return builder
         * 
         */
        public Builder sourceKeys(List<String> sourceKeys) {
            return sourceKeys(Output.of(sourceKeys));
        }

        /**
         * @param sourceKeys The source keys for the mapping.
         * 
         * @return builder
         * 
         */
        public Builder sourceKeys(String... sourceKeys) {
            return sourceKeys(List.of(sourceKeys));
        }

        public GetTagPipelineRulesetRuleMappingArgs build() {
            if ($.destinationKey == null) {
                throw new MissingRequiredPropertyException("GetTagPipelineRulesetRuleMappingArgs", "destinationKey");
            }
            if ($.ifNotExists == null) {
                throw new MissingRequiredPropertyException("GetTagPipelineRulesetRuleMappingArgs", "ifNotExists");
            }
            if ($.sourceKeys == null) {
                throw new MissingRequiredPropertyException("GetTagPipelineRulesetRuleMappingArgs", "sourceKeys");
            }
            return $;
        }
    }

}
