// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.datadog.inputs.LogsCustomPipelineProcessorArrayMapProcessorProcessorArithmeticProcessorArgs;
import com.pulumi.datadog.inputs.LogsCustomPipelineProcessorArrayMapProcessorProcessorAttributeRemapperArgs;
import com.pulumi.datadog.inputs.LogsCustomPipelineProcessorArrayMapProcessorProcessorCategoryProcessorArgs;
import com.pulumi.datadog.inputs.LogsCustomPipelineProcessorArrayMapProcessorProcessorStringBuilderProcessorArgs;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class LogsCustomPipelineProcessorArrayMapProcessorProcessorArgs extends com.pulumi.resources.ResourceArgs {

    public static final LogsCustomPipelineProcessorArrayMapProcessorProcessorArgs Empty = new LogsCustomPipelineProcessorArrayMapProcessorProcessorArgs();

    /**
     * Array-map arithmetic sub-processor.
     * 
     */
    @Import(name="arithmeticProcessor")
    private @Nullable Output<LogsCustomPipelineProcessorArrayMapProcessorProcessorArithmeticProcessorArgs> arithmeticProcessor;

    /**
     * @return Array-map arithmetic sub-processor.
     * 
     */
    public Optional<Output<LogsCustomPipelineProcessorArrayMapProcessorProcessorArithmeticProcessorArgs>> arithmeticProcessor() {
        return Optional.ofNullable(this.arithmeticProcessor);
    }

    /**
     * Array-map attribute remapper sub-processor.
     * 
     */
    @Import(name="attributeRemapper")
    private @Nullable Output<LogsCustomPipelineProcessorArrayMapProcessorProcessorAttributeRemapperArgs> attributeRemapper;

    /**
     * @return Array-map attribute remapper sub-processor.
     * 
     */
    public Optional<Output<LogsCustomPipelineProcessorArrayMapProcessorProcessorAttributeRemapperArgs>> attributeRemapper() {
        return Optional.ofNullable(this.attributeRemapper);
    }

    /**
     * Array-map category sub-processor.
     * 
     */
    @Import(name="categoryProcessor")
    private @Nullable Output<LogsCustomPipelineProcessorArrayMapProcessorProcessorCategoryProcessorArgs> categoryProcessor;

    /**
     * @return Array-map category sub-processor.
     * 
     */
    public Optional<Output<LogsCustomPipelineProcessorArrayMapProcessorProcessorCategoryProcessorArgs>> categoryProcessor() {
        return Optional.ofNullable(this.categoryProcessor);
    }

    /**
     * Array-map string builder sub-processor.
     * 
     */
    @Import(name="stringBuilderProcessor")
    private @Nullable Output<LogsCustomPipelineProcessorArrayMapProcessorProcessorStringBuilderProcessorArgs> stringBuilderProcessor;

    /**
     * @return Array-map string builder sub-processor.
     * 
     */
    public Optional<Output<LogsCustomPipelineProcessorArrayMapProcessorProcessorStringBuilderProcessorArgs>> stringBuilderProcessor() {
        return Optional.ofNullable(this.stringBuilderProcessor);
    }

    private LogsCustomPipelineProcessorArrayMapProcessorProcessorArgs() {}

    private LogsCustomPipelineProcessorArrayMapProcessorProcessorArgs(LogsCustomPipelineProcessorArrayMapProcessorProcessorArgs $) {
        this.arithmeticProcessor = $.arithmeticProcessor;
        this.attributeRemapper = $.attributeRemapper;
        this.categoryProcessor = $.categoryProcessor;
        this.stringBuilderProcessor = $.stringBuilderProcessor;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(LogsCustomPipelineProcessorArrayMapProcessorProcessorArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private LogsCustomPipelineProcessorArrayMapProcessorProcessorArgs $;

        public Builder() {
            $ = new LogsCustomPipelineProcessorArrayMapProcessorProcessorArgs();
        }

        public Builder(LogsCustomPipelineProcessorArrayMapProcessorProcessorArgs defaults) {
            $ = new LogsCustomPipelineProcessorArrayMapProcessorProcessorArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param arithmeticProcessor Array-map arithmetic sub-processor.
         * 
         * @return builder
         * 
         */
        public Builder arithmeticProcessor(@Nullable Output<LogsCustomPipelineProcessorArrayMapProcessorProcessorArithmeticProcessorArgs> arithmeticProcessor) {
            $.arithmeticProcessor = arithmeticProcessor;
            return this;
        }

        /**
         * @param arithmeticProcessor Array-map arithmetic sub-processor.
         * 
         * @return builder
         * 
         */
        public Builder arithmeticProcessor(LogsCustomPipelineProcessorArrayMapProcessorProcessorArithmeticProcessorArgs arithmeticProcessor) {
            return arithmeticProcessor(Output.of(arithmeticProcessor));
        }

        /**
         * @param attributeRemapper Array-map attribute remapper sub-processor.
         * 
         * @return builder
         * 
         */
        public Builder attributeRemapper(@Nullable Output<LogsCustomPipelineProcessorArrayMapProcessorProcessorAttributeRemapperArgs> attributeRemapper) {
            $.attributeRemapper = attributeRemapper;
            return this;
        }

        /**
         * @param attributeRemapper Array-map attribute remapper sub-processor.
         * 
         * @return builder
         * 
         */
        public Builder attributeRemapper(LogsCustomPipelineProcessorArrayMapProcessorProcessorAttributeRemapperArgs attributeRemapper) {
            return attributeRemapper(Output.of(attributeRemapper));
        }

        /**
         * @param categoryProcessor Array-map category sub-processor.
         * 
         * @return builder
         * 
         */
        public Builder categoryProcessor(@Nullable Output<LogsCustomPipelineProcessorArrayMapProcessorProcessorCategoryProcessorArgs> categoryProcessor) {
            $.categoryProcessor = categoryProcessor;
            return this;
        }

        /**
         * @param categoryProcessor Array-map category sub-processor.
         * 
         * @return builder
         * 
         */
        public Builder categoryProcessor(LogsCustomPipelineProcessorArrayMapProcessorProcessorCategoryProcessorArgs categoryProcessor) {
            return categoryProcessor(Output.of(categoryProcessor));
        }

        /**
         * @param stringBuilderProcessor Array-map string builder sub-processor.
         * 
         * @return builder
         * 
         */
        public Builder stringBuilderProcessor(@Nullable Output<LogsCustomPipelineProcessorArrayMapProcessorProcessorStringBuilderProcessorArgs> stringBuilderProcessor) {
            $.stringBuilderProcessor = stringBuilderProcessor;
            return this;
        }

        /**
         * @param stringBuilderProcessor Array-map string builder sub-processor.
         * 
         * @return builder
         * 
         */
        public Builder stringBuilderProcessor(LogsCustomPipelineProcessorArrayMapProcessorProcessorStringBuilderProcessorArgs stringBuilderProcessor) {
            return stringBuilderProcessor(Output.of(stringBuilderProcessor));
        }

        public LogsCustomPipelineProcessorArrayMapProcessorProcessorArgs build() {
            return $;
        }
    }

}
