// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.datadog.inputs.ObservabilityPipelineConfigSourcesAmazonS3AuthArgs;
import com.pulumi.datadog.inputs.ObservabilityPipelineConfigSourcesAmazonS3TlsArgs;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ObservabilityPipelineConfigSourcesAmazonS3Args extends com.pulumi.resources.ResourceArgs {

    public static final ObservabilityPipelineConfigSourcesAmazonS3Args Empty = new ObservabilityPipelineConfigSourcesAmazonS3Args();

    /**
     * AWS authentication credentials used for accessing AWS services such as S3. If omitted, the system&#39;s default credentials are used (for example, the IAM role and environment variables).
     * 
     */
    @Import(name="auth")
    private @Nullable Output<ObservabilityPipelineConfigSourcesAmazonS3AuthArgs> auth;

    /**
     * @return AWS authentication credentials used for accessing AWS services such as S3. If omitted, the system&#39;s default credentials are used (for example, the IAM role and environment variables).
     * 
     */
    public Optional<Output<ObservabilityPipelineConfigSourcesAmazonS3AuthArgs>> auth() {
        return Optional.ofNullable(this.auth);
    }

    /**
     * The unique identifier for this component. Used to reference this component in other parts of the pipeline (e.g., as input to downstream components).
     * 
     */
    @Import(name="id", required=true)
    private Output<String> id;

    /**
     * @return The unique identifier for this component. Used to reference this component in other parts of the pipeline (e.g., as input to downstream components).
     * 
     */
    public Output<String> id() {
        return this.id;
    }

    /**
     * AWS region where the S3 bucket resides.
     * 
     */
    @Import(name="region", required=true)
    private Output<String> region;

    /**
     * @return AWS region where the S3 bucket resides.
     * 
     */
    public Output<String> region() {
        return this.region;
    }

    /**
     * Configuration for enabling TLS encryption between the pipeline component and external services.
     * 
     */
    @Import(name="tls")
    private @Nullable Output<ObservabilityPipelineConfigSourcesAmazonS3TlsArgs> tls;

    /**
     * @return Configuration for enabling TLS encryption between the pipeline component and external services.
     * 
     */
    public Optional<Output<ObservabilityPipelineConfigSourcesAmazonS3TlsArgs>> tls() {
        return Optional.ofNullable(this.tls);
    }

    private ObservabilityPipelineConfigSourcesAmazonS3Args() {}

    private ObservabilityPipelineConfigSourcesAmazonS3Args(ObservabilityPipelineConfigSourcesAmazonS3Args $) {
        this.auth = $.auth;
        this.id = $.id;
        this.region = $.region;
        this.tls = $.tls;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ObservabilityPipelineConfigSourcesAmazonS3Args defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ObservabilityPipelineConfigSourcesAmazonS3Args $;

        public Builder() {
            $ = new ObservabilityPipelineConfigSourcesAmazonS3Args();
        }

        public Builder(ObservabilityPipelineConfigSourcesAmazonS3Args defaults) {
            $ = new ObservabilityPipelineConfigSourcesAmazonS3Args(Objects.requireNonNull(defaults));
        }

        /**
         * @param auth AWS authentication credentials used for accessing AWS services such as S3. If omitted, the system&#39;s default credentials are used (for example, the IAM role and environment variables).
         * 
         * @return builder
         * 
         */
        public Builder auth(@Nullable Output<ObservabilityPipelineConfigSourcesAmazonS3AuthArgs> auth) {
            $.auth = auth;
            return this;
        }

        /**
         * @param auth AWS authentication credentials used for accessing AWS services such as S3. If omitted, the system&#39;s default credentials are used (for example, the IAM role and environment variables).
         * 
         * @return builder
         * 
         */
        public Builder auth(ObservabilityPipelineConfigSourcesAmazonS3AuthArgs auth) {
            return auth(Output.of(auth));
        }

        /**
         * @param id The unique identifier for this component. Used to reference this component in other parts of the pipeline (e.g., as input to downstream components).
         * 
         * @return builder
         * 
         */
        public Builder id(Output<String> id) {
            $.id = id;
            return this;
        }

        /**
         * @param id The unique identifier for this component. Used to reference this component in other parts of the pipeline (e.g., as input to downstream components).
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            return id(Output.of(id));
        }

        /**
         * @param region AWS region where the S3 bucket resides.
         * 
         * @return builder
         * 
         */
        public Builder region(Output<String> region) {
            $.region = region;
            return this;
        }

        /**
         * @param region AWS region where the S3 bucket resides.
         * 
         * @return builder
         * 
         */
        public Builder region(String region) {
            return region(Output.of(region));
        }

        /**
         * @param tls Configuration for enabling TLS encryption between the pipeline component and external services.
         * 
         * @return builder
         * 
         */
        public Builder tls(@Nullable Output<ObservabilityPipelineConfigSourcesAmazonS3TlsArgs> tls) {
            $.tls = tls;
            return this;
        }

        /**
         * @param tls Configuration for enabling TLS encryption between the pipeline component and external services.
         * 
         * @return builder
         * 
         */
        public Builder tls(ObservabilityPipelineConfigSourcesAmazonS3TlsArgs tls) {
            return tls(Output.of(tls));
        }

        public ObservabilityPipelineConfigSourcesAmazonS3Args build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("ObservabilityPipelineConfigSourcesAmazonS3Args", "id");
            }
            if ($.region == null) {
                throw new MissingRequiredPropertyException("ObservabilityPipelineConfigSourcesAmazonS3Args", "region");
            }
            return $;
        }
    }

}
