// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ObservabilityPipelineConfigDestinationOpensearchDataStreamArgs extends com.pulumi.resources.ResourceArgs {

    public static final ObservabilityPipelineConfigDestinationOpensearchDataStreamArgs Empty = new ObservabilityPipelineConfigDestinationOpensearchDataStreamArgs();

    /**
     * The data stream dataset for your logs. This groups logs by their source or application.
     * 
     */
    @Import(name="dataset")
    private @Nullable Output<String> dataset;

    /**
     * @return The data stream dataset for your logs. This groups logs by their source or application.
     * 
     */
    public Optional<Output<String>> dataset() {
        return Optional.ofNullable(this.dataset);
    }

    /**
     * The data stream type for your logs. This determines how logs are categorized within the data stream.
     * 
     */
    @Import(name="dtype")
    private @Nullable Output<String> dtype;

    /**
     * @return The data stream type for your logs. This determines how logs are categorized within the data stream.
     * 
     */
    public Optional<Output<String>> dtype() {
        return Optional.ofNullable(this.dtype);
    }

    /**
     * The data stream namespace for your logs. This separates logs into different environments or domains.
     * 
     */
    @Import(name="namespace")
    private @Nullable Output<String> namespace;

    /**
     * @return The data stream namespace for your logs. This separates logs into different environments or domains.
     * 
     */
    public Optional<Output<String>> namespace() {
        return Optional.ofNullable(this.namespace);
    }

    private ObservabilityPipelineConfigDestinationOpensearchDataStreamArgs() {}

    private ObservabilityPipelineConfigDestinationOpensearchDataStreamArgs(ObservabilityPipelineConfigDestinationOpensearchDataStreamArgs $) {
        this.dataset = $.dataset;
        this.dtype = $.dtype;
        this.namespace = $.namespace;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ObservabilityPipelineConfigDestinationOpensearchDataStreamArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ObservabilityPipelineConfigDestinationOpensearchDataStreamArgs $;

        public Builder() {
            $ = new ObservabilityPipelineConfigDestinationOpensearchDataStreamArgs();
        }

        public Builder(ObservabilityPipelineConfigDestinationOpensearchDataStreamArgs defaults) {
            $ = new ObservabilityPipelineConfigDestinationOpensearchDataStreamArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param dataset The data stream dataset for your logs. This groups logs by their source or application.
         * 
         * @return builder
         * 
         */
        public Builder dataset(@Nullable Output<String> dataset) {
            $.dataset = dataset;
            return this;
        }

        /**
         * @param dataset The data stream dataset for your logs. This groups logs by their source or application.
         * 
         * @return builder
         * 
         */
        public Builder dataset(String dataset) {
            return dataset(Output.of(dataset));
        }

        /**
         * @param dtype The data stream type for your logs. This determines how logs are categorized within the data stream.
         * 
         * @return builder
         * 
         */
        public Builder dtype(@Nullable Output<String> dtype) {
            $.dtype = dtype;
            return this;
        }

        /**
         * @param dtype The data stream type for your logs. This determines how logs are categorized within the data stream.
         * 
         * @return builder
         * 
         */
        public Builder dtype(String dtype) {
            return dtype(Output.of(dtype));
        }

        /**
         * @param namespace The data stream namespace for your logs. This separates logs into different environments or domains.
         * 
         * @return builder
         * 
         */
        public Builder namespace(@Nullable Output<String> namespace) {
            $.namespace = namespace;
            return this;
        }

        /**
         * @param namespace The data stream namespace for your logs. This separates logs into different environments or domains.
         * 
         * @return builder
         * 
         */
        public Builder namespace(String namespace) {
            return namespace(Output.of(namespace));
        }

        public ObservabilityPipelineConfigDestinationOpensearchDataStreamArgs build() {
            return $;
        }
    }

}
