// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ObservabilityPipelineConfigDestinationAzureStorageArgs extends com.pulumi.resources.ResourceArgs {

    public static final ObservabilityPipelineConfigDestinationAzureStorageArgs Empty = new ObservabilityPipelineConfigDestinationAzureStorageArgs();

    /**
     * Optional prefix for blobs written to the container.
     * 
     */
    @Import(name="blobPrefix")
    private @Nullable Output<String> blobPrefix;

    /**
     * @return Optional prefix for blobs written to the container.
     * 
     */
    public Optional<Output<String>> blobPrefix() {
        return Optional.ofNullable(this.blobPrefix);
    }

    /**
     * The name of the Azure Blob Storage container to store logs in.
     * 
     */
    @Import(name="containerName", required=true)
    private Output<String> containerName;

    /**
     * @return The name of the Azure Blob Storage container to store logs in.
     * 
     */
    public Output<String> containerName() {
        return this.containerName;
    }

    private ObservabilityPipelineConfigDestinationAzureStorageArgs() {}

    private ObservabilityPipelineConfigDestinationAzureStorageArgs(ObservabilityPipelineConfigDestinationAzureStorageArgs $) {
        this.blobPrefix = $.blobPrefix;
        this.containerName = $.containerName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ObservabilityPipelineConfigDestinationAzureStorageArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ObservabilityPipelineConfigDestinationAzureStorageArgs $;

        public Builder() {
            $ = new ObservabilityPipelineConfigDestinationAzureStorageArgs();
        }

        public Builder(ObservabilityPipelineConfigDestinationAzureStorageArgs defaults) {
            $ = new ObservabilityPipelineConfigDestinationAzureStorageArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param blobPrefix Optional prefix for blobs written to the container.
         * 
         * @return builder
         * 
         */
        public Builder blobPrefix(@Nullable Output<String> blobPrefix) {
            $.blobPrefix = blobPrefix;
            return this;
        }

        /**
         * @param blobPrefix Optional prefix for blobs written to the container.
         * 
         * @return builder
         * 
         */
        public Builder blobPrefix(String blobPrefix) {
            return blobPrefix(Output.of(blobPrefix));
        }

        /**
         * @param containerName The name of the Azure Blob Storage container to store logs in.
         * 
         * @return builder
         * 
         */
        public Builder containerName(Output<String> containerName) {
            $.containerName = containerName;
            return this;
        }

        /**
         * @param containerName The name of the Azure Blob Storage container to store logs in.
         * 
         * @return builder
         * 
         */
        public Builder containerName(String containerName) {
            return containerName(Output.of(containerName));
        }

        public ObservabilityPipelineConfigDestinationAzureStorageArgs build() {
            if ($.containerName == null) {
                throw new MissingRequiredPropertyException("ObservabilityPipelineConfigDestinationAzureStorageArgs", "containerName");
            }
            return $;
        }
    }

}
