// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class ObservabilityPipelineConfigProcessorGroupProcessorAddEnvVarsVariableArgs extends com.pulumi.resources.ResourceArgs {

    public static final ObservabilityPipelineConfigProcessorGroupProcessorAddEnvVarsVariableArgs Empty = new ObservabilityPipelineConfigProcessorGroupProcessorAddEnvVarsVariableArgs();

    /**
     * The target field in the log event.
     * 
     */
    @Import(name="field", required=true)
    private Output<String> field;

    /**
     * @return The target field in the log event.
     * 
     */
    public Output<String> field() {
        return this.field;
    }

    /**
     * The name of the environment variable to read.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return The name of the environment variable to read.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    private ObservabilityPipelineConfigProcessorGroupProcessorAddEnvVarsVariableArgs() {}

    private ObservabilityPipelineConfigProcessorGroupProcessorAddEnvVarsVariableArgs(ObservabilityPipelineConfigProcessorGroupProcessorAddEnvVarsVariableArgs $) {
        this.field = $.field;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ObservabilityPipelineConfigProcessorGroupProcessorAddEnvVarsVariableArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ObservabilityPipelineConfigProcessorGroupProcessorAddEnvVarsVariableArgs $;

        public Builder() {
            $ = new ObservabilityPipelineConfigProcessorGroupProcessorAddEnvVarsVariableArgs();
        }

        public Builder(ObservabilityPipelineConfigProcessorGroupProcessorAddEnvVarsVariableArgs defaults) {
            $ = new ObservabilityPipelineConfigProcessorGroupProcessorAddEnvVarsVariableArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param field The target field in the log event.
         * 
         * @return builder
         * 
         */
        public Builder field(Output<String> field) {
            $.field = field;
            return this;
        }

        /**
         * @param field The target field in the log event.
         * 
         * @return builder
         * 
         */
        public Builder field(String field) {
            return field(Output.of(field));
        }

        /**
         * @param name The name of the environment variable to read.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the environment variable to read.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public ObservabilityPipelineConfigProcessorGroupProcessorAddEnvVarsVariableArgs build() {
            if ($.field == null) {
                throw new MissingRequiredPropertyException("ObservabilityPipelineConfigProcessorGroupProcessorAddEnvVarsVariableArgs", "field");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("ObservabilityPipelineConfigProcessorGroupProcessorAddEnvVarsVariableArgs", "name");
            }
            return $;
        }
    }

}
