// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.datadog.inputs.PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryComputeQueryArgs;
import com.pulumi.datadog.inputs.PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryGroupByArgs;
import com.pulumi.datadog.inputs.PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryMultiComputeArgs;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryArgs extends com.pulumi.resources.ResourceArgs {

    public static final PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryArgs Empty = new PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryArgs();

    /**
     * `computeQuery` or `multiCompute` is required. The map keys are listed below.
     * 
     */
    @Import(name="computeQuery")
    private @Nullable Output<PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryComputeQueryArgs> computeQuery;

    /**
     * @return `computeQuery` or `multiCompute` is required. The map keys are listed below.
     * 
     */
    public Optional<Output<PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryComputeQueryArgs>> computeQuery() {
        return Optional.ofNullable(this.computeQuery);
    }

    /**
     * Multiple `groupBy` blocks are allowed using the structure below.
     * 
     */
    @Import(name="groupBies")
    private @Nullable Output<List<PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryGroupByArgs>> groupBies;

    /**
     * @return Multiple `groupBy` blocks are allowed using the structure below.
     * 
     */
    public Optional<Output<List<PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryGroupByArgs>>> groupBies() {
        return Optional.ofNullable(this.groupBies);
    }

    /**
     * A comma separated-list of index names. Use `*` to query all indexes at once. [Multiple Indexes](https://docs.datadoghq.com/logs/indexes/#multiple-indexes).
     * 
     */
    @Import(name="index", required=true)
    private Output<String> index;

    /**
     * @return A comma separated-list of index names. Use `*` to query all indexes at once. [Multiple Indexes](https://docs.datadoghq.com/logs/indexes/#multiple-indexes).
     * 
     */
    public Output<String> index() {
        return this.index;
    }

    /**
     * `computeQuery` or `multiCompute` is required. Multiple `multiCompute` blocks are allowed using the structure below.
     * 
     */
    @Import(name="multiComputes")
    private @Nullable Output<List<PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryMultiComputeArgs>> multiComputes;

    /**
     * @return `computeQuery` or `multiCompute` is required. Multiple `multiCompute` blocks are allowed using the structure below.
     * 
     */
    public Optional<Output<List<PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryMultiComputeArgs>>> multiComputes() {
        return Optional.ofNullable(this.multiComputes);
    }

    /**
     * The search query to use.
     * 
     */
    @Import(name="searchQuery")
    private @Nullable Output<String> searchQuery;

    /**
     * @return The search query to use.
     * 
     */
    public Optional<Output<String>> searchQuery() {
        return Optional.ofNullable(this.searchQuery);
    }

    private PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryArgs() {}

    private PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryArgs(PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryArgs $) {
        this.computeQuery = $.computeQuery;
        this.groupBies = $.groupBies;
        this.index = $.index;
        this.multiComputes = $.multiComputes;
        this.searchQuery = $.searchQuery;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryArgs $;

        public Builder() {
            $ = new PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryArgs();
        }

        public Builder(PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryArgs defaults) {
            $ = new PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param computeQuery `computeQuery` or `multiCompute` is required. The map keys are listed below.
         * 
         * @return builder
         * 
         */
        public Builder computeQuery(@Nullable Output<PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryComputeQueryArgs> computeQuery) {
            $.computeQuery = computeQuery;
            return this;
        }

        /**
         * @param computeQuery `computeQuery` or `multiCompute` is required. The map keys are listed below.
         * 
         * @return builder
         * 
         */
        public Builder computeQuery(PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryComputeQueryArgs computeQuery) {
            return computeQuery(Output.of(computeQuery));
        }

        /**
         * @param groupBies Multiple `groupBy` blocks are allowed using the structure below.
         * 
         * @return builder
         * 
         */
        public Builder groupBies(@Nullable Output<List<PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryGroupByArgs>> groupBies) {
            $.groupBies = groupBies;
            return this;
        }

        /**
         * @param groupBies Multiple `groupBy` blocks are allowed using the structure below.
         * 
         * @return builder
         * 
         */
        public Builder groupBies(List<PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryGroupByArgs> groupBies) {
            return groupBies(Output.of(groupBies));
        }

        /**
         * @param groupBies Multiple `groupBy` blocks are allowed using the structure below.
         * 
         * @return builder
         * 
         */
        public Builder groupBies(PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryGroupByArgs... groupBies) {
            return groupBies(List.of(groupBies));
        }

        /**
         * @param index A comma separated-list of index names. Use `*` to query all indexes at once. [Multiple Indexes](https://docs.datadoghq.com/logs/indexes/#multiple-indexes).
         * 
         * @return builder
         * 
         */
        public Builder index(Output<String> index) {
            $.index = index;
            return this;
        }

        /**
         * @param index A comma separated-list of index names. Use `*` to query all indexes at once. [Multiple Indexes](https://docs.datadoghq.com/logs/indexes/#multiple-indexes).
         * 
         * @return builder
         * 
         */
        public Builder index(String index) {
            return index(Output.of(index));
        }

        /**
         * @param multiComputes `computeQuery` or `multiCompute` is required. Multiple `multiCompute` blocks are allowed using the structure below.
         * 
         * @return builder
         * 
         */
        public Builder multiComputes(@Nullable Output<List<PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryMultiComputeArgs>> multiComputes) {
            $.multiComputes = multiComputes;
            return this;
        }

        /**
         * @param multiComputes `computeQuery` or `multiCompute` is required. Multiple `multiCompute` blocks are allowed using the structure below.
         * 
         * @return builder
         * 
         */
        public Builder multiComputes(List<PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryMultiComputeArgs> multiComputes) {
            return multiComputes(Output.of(multiComputes));
        }

        /**
         * @param multiComputes `computeQuery` or `multiCompute` is required. Multiple `multiCompute` blocks are allowed using the structure below.
         * 
         * @return builder
         * 
         */
        public Builder multiComputes(PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryMultiComputeArgs... multiComputes) {
            return multiComputes(List.of(multiComputes));
        }

        /**
         * @param searchQuery The search query to use.
         * 
         * @return builder
         * 
         */
        public Builder searchQuery(@Nullable Output<String> searchQuery) {
            $.searchQuery = searchQuery;
            return this;
        }

        /**
         * @param searchQuery The search query to use.
         * 
         * @return builder
         * 
         */
        public Builder searchQuery(String searchQuery) {
            return searchQuery(Output.of(searchQuery));
        }

        public PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryArgs build() {
            if ($.index == null) {
                throw new MissingRequiredPropertyException("PowerpackV2WidgetGroupDefinitionWidgetSunburstDefinitionRequestNetworkQueryArgs", "index");
            }
            return $;
        }
    }

}
