// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.datadog.inputs.PowerpackV2WidgetScatterplotDefinitionRequestXQueryApmDependencyStatsQueryArgs;
import com.pulumi.datadog.inputs.PowerpackV2WidgetScatterplotDefinitionRequestXQueryApmResourceStatsQueryArgs;
import com.pulumi.datadog.inputs.PowerpackV2WidgetScatterplotDefinitionRequestXQueryCloudCostQueryArgs;
import com.pulumi.datadog.inputs.PowerpackV2WidgetScatterplotDefinitionRequestXQueryEventQueryArgs;
import com.pulumi.datadog.inputs.PowerpackV2WidgetScatterplotDefinitionRequestXQueryMetricQueryArgs;
import com.pulumi.datadog.inputs.PowerpackV2WidgetScatterplotDefinitionRequestXQueryProcessQueryArgs;
import com.pulumi.datadog.inputs.PowerpackV2WidgetScatterplotDefinitionRequestXQuerySloQueryArgs;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PowerpackV2WidgetScatterplotDefinitionRequestXQueryArgs extends com.pulumi.resources.ResourceArgs {

    public static final PowerpackV2WidgetScatterplotDefinitionRequestXQueryArgs Empty = new PowerpackV2WidgetScatterplotDefinitionRequestXQueryArgs();

    /**
     * The APM Dependency Stats query using formulas and functions.
     * 
     */
    @Import(name="apmDependencyStatsQuery")
    private @Nullable Output<PowerpackV2WidgetScatterplotDefinitionRequestXQueryApmDependencyStatsQueryArgs> apmDependencyStatsQuery;

    /**
     * @return The APM Dependency Stats query using formulas and functions.
     * 
     */
    public Optional<Output<PowerpackV2WidgetScatterplotDefinitionRequestXQueryApmDependencyStatsQueryArgs>> apmDependencyStatsQuery() {
        return Optional.ofNullable(this.apmDependencyStatsQuery);
    }

    /**
     * The APM Resource Stats query using formulas and functions.
     * 
     */
    @Import(name="apmResourceStatsQuery")
    private @Nullable Output<PowerpackV2WidgetScatterplotDefinitionRequestXQueryApmResourceStatsQueryArgs> apmResourceStatsQuery;

    /**
     * @return The APM Resource Stats query using formulas and functions.
     * 
     */
    public Optional<Output<PowerpackV2WidgetScatterplotDefinitionRequestXQueryApmResourceStatsQueryArgs>> apmResourceStatsQuery() {
        return Optional.ofNullable(this.apmResourceStatsQuery);
    }

    /**
     * The Cloud Cost query using formulas and functions.
     * 
     */
    @Import(name="cloudCostQuery")
    private @Nullable Output<PowerpackV2WidgetScatterplotDefinitionRequestXQueryCloudCostQueryArgs> cloudCostQuery;

    /**
     * @return The Cloud Cost query using formulas and functions.
     * 
     */
    public Optional<Output<PowerpackV2WidgetScatterplotDefinitionRequestXQueryCloudCostQueryArgs>> cloudCostQuery() {
        return Optional.ofNullable(this.cloudCostQuery);
    }

    /**
     * A timeseries formula and functions events query.
     * 
     */
    @Import(name="eventQuery")
    private @Nullable Output<PowerpackV2WidgetScatterplotDefinitionRequestXQueryEventQueryArgs> eventQuery;

    /**
     * @return A timeseries formula and functions events query.
     * 
     */
    public Optional<Output<PowerpackV2WidgetScatterplotDefinitionRequestXQueryEventQueryArgs>> eventQuery() {
        return Optional.ofNullable(this.eventQuery);
    }

    /**
     * A timeseries formula and functions metrics query.
     * 
     */
    @Import(name="metricQuery")
    private @Nullable Output<PowerpackV2WidgetScatterplotDefinitionRequestXQueryMetricQueryArgs> metricQuery;

    /**
     * @return A timeseries formula and functions metrics query.
     * 
     */
    public Optional<Output<PowerpackV2WidgetScatterplotDefinitionRequestXQueryMetricQueryArgs>> metricQuery() {
        return Optional.ofNullable(this.metricQuery);
    }

    /**
     * The process query using formulas and functions.
     * 
     */
    @Import(name="processQuery")
    private @Nullable Output<PowerpackV2WidgetScatterplotDefinitionRequestXQueryProcessQueryArgs> processQuery;

    /**
     * @return The process query using formulas and functions.
     * 
     */
    public Optional<Output<PowerpackV2WidgetScatterplotDefinitionRequestXQueryProcessQueryArgs>> processQuery() {
        return Optional.ofNullable(this.processQuery);
    }

    /**
     * The SLO query using formulas and functions.
     * 
     */
    @Import(name="sloQuery")
    private @Nullable Output<PowerpackV2WidgetScatterplotDefinitionRequestXQuerySloQueryArgs> sloQuery;

    /**
     * @return The SLO query using formulas and functions.
     * 
     */
    public Optional<Output<PowerpackV2WidgetScatterplotDefinitionRequestXQuerySloQueryArgs>> sloQuery() {
        return Optional.ofNullable(this.sloQuery);
    }

    private PowerpackV2WidgetScatterplotDefinitionRequestXQueryArgs() {}

    private PowerpackV2WidgetScatterplotDefinitionRequestXQueryArgs(PowerpackV2WidgetScatterplotDefinitionRequestXQueryArgs $) {
        this.apmDependencyStatsQuery = $.apmDependencyStatsQuery;
        this.apmResourceStatsQuery = $.apmResourceStatsQuery;
        this.cloudCostQuery = $.cloudCostQuery;
        this.eventQuery = $.eventQuery;
        this.metricQuery = $.metricQuery;
        this.processQuery = $.processQuery;
        this.sloQuery = $.sloQuery;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PowerpackV2WidgetScatterplotDefinitionRequestXQueryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PowerpackV2WidgetScatterplotDefinitionRequestXQueryArgs $;

        public Builder() {
            $ = new PowerpackV2WidgetScatterplotDefinitionRequestXQueryArgs();
        }

        public Builder(PowerpackV2WidgetScatterplotDefinitionRequestXQueryArgs defaults) {
            $ = new PowerpackV2WidgetScatterplotDefinitionRequestXQueryArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param apmDependencyStatsQuery The APM Dependency Stats query using formulas and functions.
         * 
         * @return builder
         * 
         */
        public Builder apmDependencyStatsQuery(@Nullable Output<PowerpackV2WidgetScatterplotDefinitionRequestXQueryApmDependencyStatsQueryArgs> apmDependencyStatsQuery) {
            $.apmDependencyStatsQuery = apmDependencyStatsQuery;
            return this;
        }

        /**
         * @param apmDependencyStatsQuery The APM Dependency Stats query using formulas and functions.
         * 
         * @return builder
         * 
         */
        public Builder apmDependencyStatsQuery(PowerpackV2WidgetScatterplotDefinitionRequestXQueryApmDependencyStatsQueryArgs apmDependencyStatsQuery) {
            return apmDependencyStatsQuery(Output.of(apmDependencyStatsQuery));
        }

        /**
         * @param apmResourceStatsQuery The APM Resource Stats query using formulas and functions.
         * 
         * @return builder
         * 
         */
        public Builder apmResourceStatsQuery(@Nullable Output<PowerpackV2WidgetScatterplotDefinitionRequestXQueryApmResourceStatsQueryArgs> apmResourceStatsQuery) {
            $.apmResourceStatsQuery = apmResourceStatsQuery;
            return this;
        }

        /**
         * @param apmResourceStatsQuery The APM Resource Stats query using formulas and functions.
         * 
         * @return builder
         * 
         */
        public Builder apmResourceStatsQuery(PowerpackV2WidgetScatterplotDefinitionRequestXQueryApmResourceStatsQueryArgs apmResourceStatsQuery) {
            return apmResourceStatsQuery(Output.of(apmResourceStatsQuery));
        }

        /**
         * @param cloudCostQuery The Cloud Cost query using formulas and functions.
         * 
         * @return builder
         * 
         */
        public Builder cloudCostQuery(@Nullable Output<PowerpackV2WidgetScatterplotDefinitionRequestXQueryCloudCostQueryArgs> cloudCostQuery) {
            $.cloudCostQuery = cloudCostQuery;
            return this;
        }

        /**
         * @param cloudCostQuery The Cloud Cost query using formulas and functions.
         * 
         * @return builder
         * 
         */
        public Builder cloudCostQuery(PowerpackV2WidgetScatterplotDefinitionRequestXQueryCloudCostQueryArgs cloudCostQuery) {
            return cloudCostQuery(Output.of(cloudCostQuery));
        }

        /**
         * @param eventQuery A timeseries formula and functions events query.
         * 
         * @return builder
         * 
         */
        public Builder eventQuery(@Nullable Output<PowerpackV2WidgetScatterplotDefinitionRequestXQueryEventQueryArgs> eventQuery) {
            $.eventQuery = eventQuery;
            return this;
        }

        /**
         * @param eventQuery A timeseries formula and functions events query.
         * 
         * @return builder
         * 
         */
        public Builder eventQuery(PowerpackV2WidgetScatterplotDefinitionRequestXQueryEventQueryArgs eventQuery) {
            return eventQuery(Output.of(eventQuery));
        }

        /**
         * @param metricQuery A timeseries formula and functions metrics query.
         * 
         * @return builder
         * 
         */
        public Builder metricQuery(@Nullable Output<PowerpackV2WidgetScatterplotDefinitionRequestXQueryMetricQueryArgs> metricQuery) {
            $.metricQuery = metricQuery;
            return this;
        }

        /**
         * @param metricQuery A timeseries formula and functions metrics query.
         * 
         * @return builder
         * 
         */
        public Builder metricQuery(PowerpackV2WidgetScatterplotDefinitionRequestXQueryMetricQueryArgs metricQuery) {
            return metricQuery(Output.of(metricQuery));
        }

        /**
         * @param processQuery The process query using formulas and functions.
         * 
         * @return builder
         * 
         */
        public Builder processQuery(@Nullable Output<PowerpackV2WidgetScatterplotDefinitionRequestXQueryProcessQueryArgs> processQuery) {
            $.processQuery = processQuery;
            return this;
        }

        /**
         * @param processQuery The process query using formulas and functions.
         * 
         * @return builder
         * 
         */
        public Builder processQuery(PowerpackV2WidgetScatterplotDefinitionRequestXQueryProcessQueryArgs processQuery) {
            return processQuery(Output.of(processQuery));
        }

        /**
         * @param sloQuery The SLO query using formulas and functions.
         * 
         * @return builder
         * 
         */
        public Builder sloQuery(@Nullable Output<PowerpackV2WidgetScatterplotDefinitionRequestXQuerySloQueryArgs> sloQuery) {
            $.sloQuery = sloQuery;
            return this;
        }

        /**
         * @param sloQuery The SLO query using formulas and functions.
         * 
         * @return builder
         * 
         */
        public Builder sloQuery(PowerpackV2WidgetScatterplotDefinitionRequestXQuerySloQueryArgs sloQuery) {
            return sloQuery(Output.of(sloQuery));
        }

        public PowerpackV2WidgetScatterplotDefinitionRequestXQueryArgs build() {
            return $;
        }
    }

}
