// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.datadog.outputs.DashboardV2WidgetQueryValueDefinitionRequestQueryRetentionQuerySearchCohortCriteriaBaseQuery;
import com.pulumi.datadog.outputs.DashboardV2WidgetQueryValueDefinitionRequestQueryRetentionQuerySearchCohortCriteriaTimeInterval;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.Objects;

@CustomType
public final class DashboardV2WidgetQueryValueDefinitionRequestQueryRetentionQuerySearchCohortCriteria {
    /**
     * @return Base Product Analytics event query for cohort membership.
     * 
     */
    private DashboardV2WidgetQueryValueDefinitionRequestQueryRetentionQuerySearchCohortCriteriaBaseQuery baseQuery;
    /**
     * @return Time interval used to build the cohort.
     * 
     */
    private DashboardV2WidgetQueryValueDefinitionRequestQueryRetentionQuerySearchCohortCriteriaTimeInterval timeInterval;

    private DashboardV2WidgetQueryValueDefinitionRequestQueryRetentionQuerySearchCohortCriteria() {}
    /**
     * @return Base Product Analytics event query for cohort membership.
     * 
     */
    public DashboardV2WidgetQueryValueDefinitionRequestQueryRetentionQuerySearchCohortCriteriaBaseQuery baseQuery() {
        return this.baseQuery;
    }
    /**
     * @return Time interval used to build the cohort.
     * 
     */
    public DashboardV2WidgetQueryValueDefinitionRequestQueryRetentionQuerySearchCohortCriteriaTimeInterval timeInterval() {
        return this.timeInterval;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DashboardV2WidgetQueryValueDefinitionRequestQueryRetentionQuerySearchCohortCriteria defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private DashboardV2WidgetQueryValueDefinitionRequestQueryRetentionQuerySearchCohortCriteriaBaseQuery baseQuery;
        private DashboardV2WidgetQueryValueDefinitionRequestQueryRetentionQuerySearchCohortCriteriaTimeInterval timeInterval;
        public Builder() {}
        public Builder(DashboardV2WidgetQueryValueDefinitionRequestQueryRetentionQuerySearchCohortCriteria defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.baseQuery = defaults.baseQuery;
    	      this.timeInterval = defaults.timeInterval;
        }

        @CustomType.Setter
        public Builder baseQuery(DashboardV2WidgetQueryValueDefinitionRequestQueryRetentionQuerySearchCohortCriteriaBaseQuery baseQuery) {
            if (baseQuery == null) {
              throw new MissingRequiredPropertyException("DashboardV2WidgetQueryValueDefinitionRequestQueryRetentionQuerySearchCohortCriteria", "baseQuery");
            }
            this.baseQuery = baseQuery;
            return this;
        }
        @CustomType.Setter
        public Builder timeInterval(DashboardV2WidgetQueryValueDefinitionRequestQueryRetentionQuerySearchCohortCriteriaTimeInterval timeInterval) {
            if (timeInterval == null) {
              throw new MissingRequiredPropertyException("DashboardV2WidgetQueryValueDefinitionRequestQueryRetentionQuerySearchCohortCriteria", "timeInterval");
            }
            this.timeInterval = timeInterval;
            return this;
        }
        public DashboardV2WidgetQueryValueDefinitionRequestQueryRetentionQuerySearchCohortCriteria build() {
            final var _resultValue = new DashboardV2WidgetQueryValueDefinitionRequestQueryRetentionQuerySearchCohortCriteria();
            _resultValue.baseQuery = baseQuery;
            _resultValue.timeInterval = timeInterval;
            return _resultValue;
        }
    }
}
