// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.datadog.outputs.DashboardWidgetChangeDefinitionRequestApmQueryComputeQuery;
import com.pulumi.datadog.outputs.DashboardWidgetChangeDefinitionRequestApmQueryGroupBy;
import com.pulumi.datadog.outputs.DashboardWidgetChangeDefinitionRequestApmQueryMultiCompute;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DashboardWidgetChangeDefinitionRequestApmQuery {
    private @Nullable DashboardWidgetChangeDefinitionRequestApmQueryComputeQuery computeQuery;
    private @Nullable List<DashboardWidgetChangeDefinitionRequestApmQueryGroupBy> groupBies;
    private String index;
    private @Nullable List<DashboardWidgetChangeDefinitionRequestApmQueryMultiCompute> multiComputes;
    private @Nullable String searchQuery;

    private DashboardWidgetChangeDefinitionRequestApmQuery() {}
    public Optional<DashboardWidgetChangeDefinitionRequestApmQueryComputeQuery> computeQuery() {
        return Optional.ofNullable(this.computeQuery);
    }
    public List<DashboardWidgetChangeDefinitionRequestApmQueryGroupBy> groupBies() {
        return this.groupBies == null ? List.of() : this.groupBies;
    }
    public String index() {
        return this.index;
    }
    public List<DashboardWidgetChangeDefinitionRequestApmQueryMultiCompute> multiComputes() {
        return this.multiComputes == null ? List.of() : this.multiComputes;
    }
    public Optional<String> searchQuery() {
        return Optional.ofNullable(this.searchQuery);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DashboardWidgetChangeDefinitionRequestApmQuery defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable DashboardWidgetChangeDefinitionRequestApmQueryComputeQuery computeQuery;
        private @Nullable List<DashboardWidgetChangeDefinitionRequestApmQueryGroupBy> groupBies;
        private String index;
        private @Nullable List<DashboardWidgetChangeDefinitionRequestApmQueryMultiCompute> multiComputes;
        private @Nullable String searchQuery;
        public Builder() {}
        public Builder(DashboardWidgetChangeDefinitionRequestApmQuery defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.computeQuery = defaults.computeQuery;
    	      this.groupBies = defaults.groupBies;
    	      this.index = defaults.index;
    	      this.multiComputes = defaults.multiComputes;
    	      this.searchQuery = defaults.searchQuery;
        }

        @CustomType.Setter
        public Builder computeQuery(@Nullable DashboardWidgetChangeDefinitionRequestApmQueryComputeQuery computeQuery) {
            this.computeQuery = computeQuery;
            return this;
        }
        @CustomType.Setter
        public Builder groupBies(@Nullable List<DashboardWidgetChangeDefinitionRequestApmQueryGroupBy> groupBies) {
            this.groupBies = groupBies;
            return this;
        }
        public Builder groupBies(DashboardWidgetChangeDefinitionRequestApmQueryGroupBy... groupBies) {
            return groupBies(List.of(groupBies));
        }
        @CustomType.Setter
        public Builder index(String index) {
            this.index = Objects.requireNonNull(index);
            return this;
        }
        @CustomType.Setter
        public Builder multiComputes(@Nullable List<DashboardWidgetChangeDefinitionRequestApmQueryMultiCompute> multiComputes) {
            this.multiComputes = multiComputes;
            return this;
        }
        public Builder multiComputes(DashboardWidgetChangeDefinitionRequestApmQueryMultiCompute... multiComputes) {
            return multiComputes(List.of(multiComputes));
        }
        @CustomType.Setter
        public Builder searchQuery(@Nullable String searchQuery) {
            this.searchQuery = searchQuery;
            return this;
        }
        public DashboardWidgetChangeDefinitionRequestApmQuery build() {
            final var o = new DashboardWidgetChangeDefinitionRequestApmQuery();
            o.computeQuery = computeQuery;
            o.groupBies = groupBies;
            o.index = index;
            o.multiComputes = multiComputes;
            o.searchQuery = searchQuery;
            return o;
        }
    }
}
