// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.datadog.outputs.DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQuerySearch;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQuery {
    /**
     * @return Data source for the Product Analytics event query. Valid values are `productAnalytics`.
     * 
     */
    private String dataSource;
    /**
     * @return Search configuration for the Product Analytics event query.
     * 
     */
    private DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQuerySearch search;

    private DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQuery() {}
    /**
     * @return Data source for the Product Analytics event query. Valid values are `productAnalytics`.
     * 
     */
    public String dataSource() {
        return this.dataSource;
    }
    /**
     * @return Search configuration for the Product Analytics event query.
     * 
     */
    public DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQuerySearch search() {
        return this.search;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQuery defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String dataSource;
        private DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQuerySearch search;
        public Builder() {}
        public Builder(DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQuery defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.dataSource = defaults.dataSource;
    	      this.search = defaults.search;
        }

        @CustomType.Setter
        public Builder dataSource(String dataSource) {
            if (dataSource == null) {
              throw new MissingRequiredPropertyException("DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQuery", "dataSource");
            }
            this.dataSource = dataSource;
            return this;
        }
        @CustomType.Setter
        public Builder search(DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQuerySearch search) {
            if (search == null) {
              throw new MissingRequiredPropertyException("DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQuery", "search");
            }
            this.search = search;
            return this;
        }
        public DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQuery build() {
            final var _resultValue = new DashboardV2WidgetGroupDefinitionWidgetCohortDefinitionRequestQuerySearchCohortCriteriaBaseQuery();
            _resultValue.dataSource = dataSource;
            _resultValue.search = search;
            return _resultValue;
        }
    }
}
