// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.datadog.outputs.LogsCustomPipelineProcessorArrayMapProcessorProcessor;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class LogsCustomPipelineProcessorArrayMapProcessor {
    /**
     * @return If the processor is enabled.
     * 
     */
    private @Nullable Boolean isEnabled;
    /**
     * @return Name of the processor.
     * 
     */
    private @Nullable String name;
    /**
     * @return Remove or preserve the source array after processing. Defaults to `true`.
     * 
     */
    private @Nullable Boolean preserveSource;
    /**
     * @return Sub-processors applied to each element. Allowed types: attribute*remapper, string*builder*processor, arithmetic*processor, category*processor.
     * 
     */
    private List<LogsCustomPipelineProcessorArrayMapProcessorProcessor> processors;
    /**
     * @return Attribute path of the source array.
     * 
     */
    private String source;
    /**
     * @return Attribute path of the output array.
     * 
     */
    private String target;

    private LogsCustomPipelineProcessorArrayMapProcessor() {}
    /**
     * @return If the processor is enabled.
     * 
     */
    public Optional<Boolean> isEnabled() {
        return Optional.ofNullable(this.isEnabled);
    }
    /**
     * @return Name of the processor.
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    /**
     * @return Remove or preserve the source array after processing. Defaults to `true`.
     * 
     */
    public Optional<Boolean> preserveSource() {
        return Optional.ofNullable(this.preserveSource);
    }
    /**
     * @return Sub-processors applied to each element. Allowed types: attribute*remapper, string*builder*processor, arithmetic*processor, category*processor.
     * 
     */
    public List<LogsCustomPipelineProcessorArrayMapProcessorProcessor> processors() {
        return this.processors;
    }
    /**
     * @return Attribute path of the source array.
     * 
     */
    public String source() {
        return this.source;
    }
    /**
     * @return Attribute path of the output array.
     * 
     */
    public String target() {
        return this.target;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(LogsCustomPipelineProcessorArrayMapProcessor defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean isEnabled;
        private @Nullable String name;
        private @Nullable Boolean preserveSource;
        private List<LogsCustomPipelineProcessorArrayMapProcessorProcessor> processors;
        private String source;
        private String target;
        public Builder() {}
        public Builder(LogsCustomPipelineProcessorArrayMapProcessor defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.isEnabled = defaults.isEnabled;
    	      this.name = defaults.name;
    	      this.preserveSource = defaults.preserveSource;
    	      this.processors = defaults.processors;
    	      this.source = defaults.source;
    	      this.target = defaults.target;
        }

        @CustomType.Setter
        public Builder isEnabled(@Nullable Boolean isEnabled) {

            this.isEnabled = isEnabled;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder preserveSource(@Nullable Boolean preserveSource) {

            this.preserveSource = preserveSource;
            return this;
        }
        @CustomType.Setter
        public Builder processors(List<LogsCustomPipelineProcessorArrayMapProcessorProcessor> processors) {
            if (processors == null) {
              throw new MissingRequiredPropertyException("LogsCustomPipelineProcessorArrayMapProcessor", "processors");
            }
            this.processors = processors;
            return this;
        }
        public Builder processors(LogsCustomPipelineProcessorArrayMapProcessorProcessor... processors) {
            return processors(List.of(processors));
        }
        @CustomType.Setter
        public Builder source(String source) {
            if (source == null) {
              throw new MissingRequiredPropertyException("LogsCustomPipelineProcessorArrayMapProcessor", "source");
            }
            this.source = source;
            return this;
        }
        @CustomType.Setter
        public Builder target(String target) {
            if (target == null) {
              throw new MissingRequiredPropertyException("LogsCustomPipelineProcessorArrayMapProcessor", "target");
            }
            this.target = target;
            return this;
        }
        public LogsCustomPipelineProcessorArrayMapProcessor build() {
            final var _resultValue = new LogsCustomPipelineProcessorArrayMapProcessor();
            _resultValue.isEnabled = isEnabled;
            _resultValue.name = name;
            _resultValue.preserveSource = preserveSource;
            _resultValue.processors = processors;
            _resultValue.source = source;
            _resultValue.target = target;
            return _resultValue;
        }
    }
}
