// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.datadog.outputs.ObservabilityPipelineConfigDestinationOpentelemetryBuffer;
import com.pulumi.datadog.outputs.ObservabilityPipelineConfigDestinationOpentelemetryTls;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ObservabilityPipelineConfigDestinationOpentelemetry {
    /**
     * @return Configuration for buffer settings on destination components. Exactly one of `disk` or `memory` must be specified.
     * 
     */
    private @Nullable ObservabilityPipelineConfigDestinationOpentelemetryBuffer buffer;
    /**
     * @return Environment variable name containing the URI of the OTLP HTTP endpoint to send metrics to.
     * 
     */
    private @Nullable String httpClientUriKey;
    /**
     * @return Configuration for enabling TLS encryption between the pipeline component and external services.
     * 
     */
    private @Nullable ObservabilityPipelineConfigDestinationOpentelemetryTls tls;

    private ObservabilityPipelineConfigDestinationOpentelemetry() {}
    /**
     * @return Configuration for buffer settings on destination components. Exactly one of `disk` or `memory` must be specified.
     * 
     */
    public Optional<ObservabilityPipelineConfigDestinationOpentelemetryBuffer> buffer() {
        return Optional.ofNullable(this.buffer);
    }
    /**
     * @return Environment variable name containing the URI of the OTLP HTTP endpoint to send metrics to.
     * 
     */
    public Optional<String> httpClientUriKey() {
        return Optional.ofNullable(this.httpClientUriKey);
    }
    /**
     * @return Configuration for enabling TLS encryption between the pipeline component and external services.
     * 
     */
    public Optional<ObservabilityPipelineConfigDestinationOpentelemetryTls> tls() {
        return Optional.ofNullable(this.tls);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ObservabilityPipelineConfigDestinationOpentelemetry defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable ObservabilityPipelineConfigDestinationOpentelemetryBuffer buffer;
        private @Nullable String httpClientUriKey;
        private @Nullable ObservabilityPipelineConfigDestinationOpentelemetryTls tls;
        public Builder() {}
        public Builder(ObservabilityPipelineConfigDestinationOpentelemetry defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.buffer = defaults.buffer;
    	      this.httpClientUriKey = defaults.httpClientUriKey;
    	      this.tls = defaults.tls;
        }

        @CustomType.Setter
        public Builder buffer(@Nullable ObservabilityPipelineConfigDestinationOpentelemetryBuffer buffer) {

            this.buffer = buffer;
            return this;
        }
        @CustomType.Setter
        public Builder httpClientUriKey(@Nullable String httpClientUriKey) {

            this.httpClientUriKey = httpClientUriKey;
            return this;
        }
        @CustomType.Setter
        public Builder tls(@Nullable ObservabilityPipelineConfigDestinationOpentelemetryTls tls) {

            this.tls = tls;
            return this;
        }
        public ObservabilityPipelineConfigDestinationOpentelemetry build() {
            final var _resultValue = new ObservabilityPipelineConfigDestinationOpentelemetry();
            _resultValue.buffer = buffer;
            _resultValue.httpClientUriKey = httpClientUriKey;
            _resultValue.tls = tls;
            return _resultValue;
        }
    }
}
