// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class ObservabilityPipelineConfigSourcesGooglePubsubAuth {
    /**
     * @return Path to the GCP service account key file.
     * 
     */
    private String credentialsFile;

    private ObservabilityPipelineConfigSourcesGooglePubsubAuth() {}
    /**
     * @return Path to the GCP service account key file.
     * 
     */
    public String credentialsFile() {
        return this.credentialsFile;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ObservabilityPipelineConfigSourcesGooglePubsubAuth defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String credentialsFile;
        public Builder() {}
        public Builder(ObservabilityPipelineConfigSourcesGooglePubsubAuth defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.credentialsFile = defaults.credentialsFile;
        }

        @CustomType.Setter
        public Builder credentialsFile(String credentialsFile) {
            if (credentialsFile == null) {
              throw new MissingRequiredPropertyException("ObservabilityPipelineConfigSourcesGooglePubsubAuth", "credentialsFile");
            }
            this.credentialsFile = credentialsFile;
            return this;
        }
        public ObservabilityPipelineConfigSourcesGooglePubsubAuth build() {
            final var _resultValue = new ObservabilityPipelineConfigSourcesGooglePubsubAuth();
            _resultValue.credentialsFile = credentialsFile;
            return _resultValue;
        }
    }
}
