// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.datadog.outputs.PowerpackV2WidgetQueryTableDefinitionRequestQueryRetentionQuerySearchCohortCriteriaBaseQuery;
import com.pulumi.datadog.outputs.PowerpackV2WidgetQueryTableDefinitionRequestQueryRetentionQuerySearchCohortCriteriaTimeInterval;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.Objects;

@CustomType
public final class PowerpackV2WidgetQueryTableDefinitionRequestQueryRetentionQuerySearchCohortCriteria {
    /**
     * @return Base Product Analytics event query for cohort membership.
     * 
     */
    private PowerpackV2WidgetQueryTableDefinitionRequestQueryRetentionQuerySearchCohortCriteriaBaseQuery baseQuery;
    /**
     * @return Time interval used to build the cohort.
     * 
     */
    private PowerpackV2WidgetQueryTableDefinitionRequestQueryRetentionQuerySearchCohortCriteriaTimeInterval timeInterval;

    private PowerpackV2WidgetQueryTableDefinitionRequestQueryRetentionQuerySearchCohortCriteria() {}
    /**
     * @return Base Product Analytics event query for cohort membership.
     * 
     */
    public PowerpackV2WidgetQueryTableDefinitionRequestQueryRetentionQuerySearchCohortCriteriaBaseQuery baseQuery() {
        return this.baseQuery;
    }
    /**
     * @return Time interval used to build the cohort.
     * 
     */
    public PowerpackV2WidgetQueryTableDefinitionRequestQueryRetentionQuerySearchCohortCriteriaTimeInterval timeInterval() {
        return this.timeInterval;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PowerpackV2WidgetQueryTableDefinitionRequestQueryRetentionQuerySearchCohortCriteria defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private PowerpackV2WidgetQueryTableDefinitionRequestQueryRetentionQuerySearchCohortCriteriaBaseQuery baseQuery;
        private PowerpackV2WidgetQueryTableDefinitionRequestQueryRetentionQuerySearchCohortCriteriaTimeInterval timeInterval;
        public Builder() {}
        public Builder(PowerpackV2WidgetQueryTableDefinitionRequestQueryRetentionQuerySearchCohortCriteria defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.baseQuery = defaults.baseQuery;
    	      this.timeInterval = defaults.timeInterval;
        }

        @CustomType.Setter
        public Builder baseQuery(PowerpackV2WidgetQueryTableDefinitionRequestQueryRetentionQuerySearchCohortCriteriaBaseQuery baseQuery) {
            if (baseQuery == null) {
              throw new MissingRequiredPropertyException("PowerpackV2WidgetQueryTableDefinitionRequestQueryRetentionQuerySearchCohortCriteria", "baseQuery");
            }
            this.baseQuery = baseQuery;
            return this;
        }
        @CustomType.Setter
        public Builder timeInterval(PowerpackV2WidgetQueryTableDefinitionRequestQueryRetentionQuerySearchCohortCriteriaTimeInterval timeInterval) {
            if (timeInterval == null) {
              throw new MissingRequiredPropertyException("PowerpackV2WidgetQueryTableDefinitionRequestQueryRetentionQuerySearchCohortCriteria", "timeInterval");
            }
            this.timeInterval = timeInterval;
            return this;
        }
        public PowerpackV2WidgetQueryTableDefinitionRequestQueryRetentionQuerySearchCohortCriteria build() {
            final var _resultValue = new PowerpackV2WidgetQueryTableDefinitionRequestQueryRetentionQuerySearchCohortCriteria();
            _resultValue.baseQuery = baseQuery;
            _resultValue.timeInterval = timeInterval;
            return _resultValue;
        }
    }
}
