// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.datadog.outputs.PowerpackV2WidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchReturnCriteriaBaseQuerySearch;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class PowerpackV2WidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchReturnCriteriaBaseQuery {
    /**
     * @return Data source for the Product Analytics event query. Valid values are `productAnalytics`.
     * 
     */
    private String dataSource;
    /**
     * @return Search configuration for the Product Analytics event query.
     * 
     */
    private PowerpackV2WidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchReturnCriteriaBaseQuerySearch search;

    private PowerpackV2WidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchReturnCriteriaBaseQuery() {}
    /**
     * @return Data source for the Product Analytics event query. Valid values are `productAnalytics`.
     * 
     */
    public String dataSource() {
        return this.dataSource;
    }
    /**
     * @return Search configuration for the Product Analytics event query.
     * 
     */
    public PowerpackV2WidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchReturnCriteriaBaseQuerySearch search() {
        return this.search;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PowerpackV2WidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchReturnCriteriaBaseQuery defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String dataSource;
        private PowerpackV2WidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchReturnCriteriaBaseQuerySearch search;
        public Builder() {}
        public Builder(PowerpackV2WidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchReturnCriteriaBaseQuery defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.dataSource = defaults.dataSource;
    	      this.search = defaults.search;
        }

        @CustomType.Setter
        public Builder dataSource(String dataSource) {
            if (dataSource == null) {
              throw new MissingRequiredPropertyException("PowerpackV2WidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchReturnCriteriaBaseQuery", "dataSource");
            }
            this.dataSource = dataSource;
            return this;
        }
        @CustomType.Setter
        public Builder search(PowerpackV2WidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchReturnCriteriaBaseQuerySearch search) {
            if (search == null) {
              throw new MissingRequiredPropertyException("PowerpackV2WidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchReturnCriteriaBaseQuery", "search");
            }
            this.search = search;
            return this;
        }
        public PowerpackV2WidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchReturnCriteriaBaseQuery build() {
            final var _resultValue = new PowerpackV2WidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchReturnCriteriaBaseQuery();
            _resultValue.dataSource = dataSource;
            _resultValue.search = search;
            return _resultValue;
        }
    }
}
