// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.datadog.outputs.PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchCohortCriteriaBaseQuery;
import com.pulumi.datadog.outputs.PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchCohortCriteriaTimeInterval;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.Objects;

@CustomType
public final class PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchCohortCriteria {
    /**
     * @return Base Product Analytics event query for cohort membership.
     * 
     */
    private PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchCohortCriteriaBaseQuery baseQuery;
    /**
     * @return Time interval used to build the cohort.
     * 
     */
    private PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchCohortCriteriaTimeInterval timeInterval;

    private PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchCohortCriteria() {}
    /**
     * @return Base Product Analytics event query for cohort membership.
     * 
     */
    public PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchCohortCriteriaBaseQuery baseQuery() {
        return this.baseQuery;
    }
    /**
     * @return Time interval used to build the cohort.
     * 
     */
    public PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchCohortCriteriaTimeInterval timeInterval() {
        return this.timeInterval;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchCohortCriteria defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchCohortCriteriaBaseQuery baseQuery;
        private PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchCohortCriteriaTimeInterval timeInterval;
        public Builder() {}
        public Builder(PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchCohortCriteria defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.baseQuery = defaults.baseQuery;
    	      this.timeInterval = defaults.timeInterval;
        }

        @CustomType.Setter
        public Builder baseQuery(PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchCohortCriteriaBaseQuery baseQuery) {
            if (baseQuery == null) {
              throw new MissingRequiredPropertyException("PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchCohortCriteria", "baseQuery");
            }
            this.baseQuery = baseQuery;
            return this;
        }
        @CustomType.Setter
        public Builder timeInterval(PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchCohortCriteriaTimeInterval timeInterval) {
            if (timeInterval == null) {
              throw new MissingRequiredPropertyException("PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchCohortCriteria", "timeInterval");
            }
            this.timeInterval = timeInterval;
            return this;
        }
        public PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchCohortCriteria build() {
            final var _resultValue = new PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYQueryRetentionQuerySearchCohortCriteria();
            _resultValue.baseQuery = baseQuery;
            _resultValue.timeInterval = timeInterval;
            return _resultValue;
        }
    }
}
