// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class PowerpackV2WidgetSankeyDefinitionRequestNetworkRequestQueryCompute {
    /**
     * @return The aggregation method.
     * 
     */
    private String aggregation;
    /**
     * @return The metric to aggregate.
     * 
     */
    private String metric;

    private PowerpackV2WidgetSankeyDefinitionRequestNetworkRequestQueryCompute() {}
    /**
     * @return The aggregation method.
     * 
     */
    public String aggregation() {
        return this.aggregation;
    }
    /**
     * @return The metric to aggregate.
     * 
     */
    public String metric() {
        return this.metric;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PowerpackV2WidgetSankeyDefinitionRequestNetworkRequestQueryCompute defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String aggregation;
        private String metric;
        public Builder() {}
        public Builder(PowerpackV2WidgetSankeyDefinitionRequestNetworkRequestQueryCompute defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.aggregation = defaults.aggregation;
    	      this.metric = defaults.metric;
        }

        @CustomType.Setter
        public Builder aggregation(String aggregation) {
            if (aggregation == null) {
              throw new MissingRequiredPropertyException("PowerpackV2WidgetSankeyDefinitionRequestNetworkRequestQueryCompute", "aggregation");
            }
            this.aggregation = aggregation;
            return this;
        }
        @CustomType.Setter
        public Builder metric(String metric) {
            if (metric == null) {
              throw new MissingRequiredPropertyException("PowerpackV2WidgetSankeyDefinitionRequestNetworkRequestQueryCompute", "metric");
            }
            this.metric = metric;
            return this;
        }
        public PowerpackV2WidgetSankeyDefinitionRequestNetworkRequestQueryCompute build() {
            final var _resultValue = new PowerpackV2WidgetSankeyDefinitionRequestNetworkRequestQueryCompute();
            _resultValue.aggregation = aggregation;
            _resultValue.metric = metric;
            return _resultValue;
        }
    }
}
