// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class ServiceLevelObjectiveQuery {
    /**
     * @return The sum of the `total` events.
     * 
     */
    private String denominator;
    /**
     * @return The sum of all the `good` events.
     * 
     */
    private String numerator;

    private ServiceLevelObjectiveQuery() {}
    /**
     * @return The sum of the `total` events.
     * 
     */
    public String denominator() {
        return this.denominator;
    }
    /**
     * @return The sum of all the `good` events.
     * 
     */
    public String numerator() {
        return this.numerator;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ServiceLevelObjectiveQuery defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String denominator;
        private String numerator;
        public Builder() {}
        public Builder(ServiceLevelObjectiveQuery defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.denominator = defaults.denominator;
    	      this.numerator = defaults.numerator;
        }

        @CustomType.Setter
        public Builder denominator(String denominator) {
            if (denominator == null) {
              throw new MissingRequiredPropertyException("ServiceLevelObjectiveQuery", "denominator");
            }
            this.denominator = denominator;
            return this;
        }
        @CustomType.Setter
        public Builder numerator(String numerator) {
            if (numerator == null) {
              throw new MissingRequiredPropertyException("ServiceLevelObjectiveQuery", "numerator");
            }
            this.numerator = numerator;
            return this;
        }
        public ServiceLevelObjectiveQuery build() {
            final var _resultValue = new ServiceLevelObjectiveQuery();
            _resultValue.denominator = denominator;
            _resultValue.numerator = numerator;
            return _resultValue;
        }
    }
}
