// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.datadog.outputs.SyntheticsTestBrowserStepParams;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class SyntheticsTestBrowserStep {
    private @Nullable Boolean allowFailure;
    private @Nullable Boolean forceElementUpdate;
    private @Nullable Boolean isCritical;
    private String name;
    private SyntheticsTestBrowserStepParams params;
    private @Nullable Integer timeout;
    private String type;

    private SyntheticsTestBrowserStep() {}
    public Optional<Boolean> allowFailure() {
        return Optional.ofNullable(this.allowFailure);
    }
    public Optional<Boolean> forceElementUpdate() {
        return Optional.ofNullable(this.forceElementUpdate);
    }
    public Optional<Boolean> isCritical() {
        return Optional.ofNullable(this.isCritical);
    }
    public String name() {
        return this.name;
    }
    public SyntheticsTestBrowserStepParams params() {
        return this.params;
    }
    public Optional<Integer> timeout() {
        return Optional.ofNullable(this.timeout);
    }
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SyntheticsTestBrowserStep defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean allowFailure;
        private @Nullable Boolean forceElementUpdate;
        private @Nullable Boolean isCritical;
        private String name;
        private SyntheticsTestBrowserStepParams params;
        private @Nullable Integer timeout;
        private String type;
        public Builder() {}
        public Builder(SyntheticsTestBrowserStep defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.allowFailure = defaults.allowFailure;
    	      this.forceElementUpdate = defaults.forceElementUpdate;
    	      this.isCritical = defaults.isCritical;
    	      this.name = defaults.name;
    	      this.params = defaults.params;
    	      this.timeout = defaults.timeout;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder allowFailure(@Nullable Boolean allowFailure) {
            this.allowFailure = allowFailure;
            return this;
        }
        @CustomType.Setter
        public Builder forceElementUpdate(@Nullable Boolean forceElementUpdate) {
            this.forceElementUpdate = forceElementUpdate;
            return this;
        }
        @CustomType.Setter
        public Builder isCritical(@Nullable Boolean isCritical) {
            this.isCritical = isCritical;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        @CustomType.Setter
        public Builder params(SyntheticsTestBrowserStepParams params) {
            this.params = Objects.requireNonNull(params);
            return this;
        }
        @CustomType.Setter
        public Builder timeout(@Nullable Integer timeout) {
            this.timeout = timeout;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }
        public SyntheticsTestBrowserStep build() {
            final var o = new SyntheticsTestBrowserStep();
            o.allowFailure = allowFailure;
            o.forceElementUpdate = forceElementUpdate;
            o.isCritical = isCritical;
            o.name = name;
            o.params = params;
            o.timeout = timeout;
            o.type = type;
            return o;
        }
    }
}
