// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.datadog.outputs.TeamSyncSelectionStateExternalId;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class TeamSyncSelectionState {
    /**
     * @return The external identifier for a team or organization in the source platform.
     * 
     */
    private TeamSyncSelectionStateExternalId externalId;
    /**
     * @return The operation to perform on the selected hierarchy. Valid values are `include`. Defaults to `&#34;include&#34;`.
     * 
     */
    private @Nullable String operation;
    /**
     * @return The scope of the selection. Valid values are `subtree`. Defaults to `&#34;subtree&#34;`.
     * 
     */
    private @Nullable String scope;

    private TeamSyncSelectionState() {}
    /**
     * @return The external identifier for a team or organization in the source platform.
     * 
     */
    public TeamSyncSelectionStateExternalId externalId() {
        return this.externalId;
    }
    /**
     * @return The operation to perform on the selected hierarchy. Valid values are `include`. Defaults to `&#34;include&#34;`.
     * 
     */
    public Optional<String> operation() {
        return Optional.ofNullable(this.operation);
    }
    /**
     * @return The scope of the selection. Valid values are `subtree`. Defaults to `&#34;subtree&#34;`.
     * 
     */
    public Optional<String> scope() {
        return Optional.ofNullable(this.scope);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(TeamSyncSelectionState defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private TeamSyncSelectionStateExternalId externalId;
        private @Nullable String operation;
        private @Nullable String scope;
        public Builder() {}
        public Builder(TeamSyncSelectionState defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.externalId = defaults.externalId;
    	      this.operation = defaults.operation;
    	      this.scope = defaults.scope;
        }

        @CustomType.Setter
        public Builder externalId(TeamSyncSelectionStateExternalId externalId) {
            if (externalId == null) {
              throw new MissingRequiredPropertyException("TeamSyncSelectionState", "externalId");
            }
            this.externalId = externalId;
            return this;
        }
        @CustomType.Setter
        public Builder operation(@Nullable String operation) {

            this.operation = operation;
            return this;
        }
        @CustomType.Setter
        public Builder scope(@Nullable String scope) {

            this.scope = scope;
            return this;
        }
        public TeamSyncSelectionState build() {
            final var _resultValue = new TeamSyncSelectionState();
            _resultValue.externalId = externalId;
            _resultValue.operation = operation;
            _resultValue.scope = scope;
            return _resultValue;
        }
    }
}
