// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.datadog.databricks.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.datadog.databricks.inputs.IntegrationAccountDataflowsDatabricksDataObservabilityQualityMonitoringSettingsArgs;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class IntegrationAccountDataflowsDatabricksDataObservabilityQualityMonitoringArgs extends com.pulumi.resources.ResourceArgs {

    public static final IntegrationAccountDataflowsDatabricksDataObservabilityQualityMonitoringArgs Empty = new IntegrationAccountDataflowsDatabricksDataObservabilityQualityMonitoringArgs();

    /**
     * Whether Datadog collects this data.
     * 
     */
    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    /**
     * @return Whether Datadog collects this data.
     * 
     */
    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * Settings of the Data Observability dataflow.
     * 
     */
    @Import(name="settings")
    private @Nullable Output<IntegrationAccountDataflowsDatabricksDataObservabilityQualityMonitoringSettingsArgs> settings;

    /**
     * @return Settings of the Data Observability dataflow.
     * 
     */
    public Optional<Output<IntegrationAccountDataflowsDatabricksDataObservabilityQualityMonitoringSettingsArgs>> settings() {
        return Optional.ofNullable(this.settings);
    }

    private IntegrationAccountDataflowsDatabricksDataObservabilityQualityMonitoringArgs() {}

    private IntegrationAccountDataflowsDatabricksDataObservabilityQualityMonitoringArgs(IntegrationAccountDataflowsDatabricksDataObservabilityQualityMonitoringArgs $) {
        this.enabled = $.enabled;
        this.settings = $.settings;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(IntegrationAccountDataflowsDatabricksDataObservabilityQualityMonitoringArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private IntegrationAccountDataflowsDatabricksDataObservabilityQualityMonitoringArgs $;

        public Builder() {
            $ = new IntegrationAccountDataflowsDatabricksDataObservabilityQualityMonitoringArgs();
        }

        public Builder(IntegrationAccountDataflowsDatabricksDataObservabilityQualityMonitoringArgs defaults) {
            $ = new IntegrationAccountDataflowsDatabricksDataObservabilityQualityMonitoringArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param enabled Whether Datadog collects this data.
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled Whether Datadog collects this data.
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param settings Settings of the Data Observability dataflow.
         * 
         * @return builder
         * 
         */
        public Builder settings(@Nullable Output<IntegrationAccountDataflowsDatabricksDataObservabilityQualityMonitoringSettingsArgs> settings) {
            $.settings = settings;
            return this;
        }

        /**
         * @param settings Settings of the Data Observability dataflow.
         * 
         * @return builder
         * 
         */
        public Builder settings(IntegrationAccountDataflowsDatabricksDataObservabilityQualityMonitoringSettingsArgs settings) {
            return settings(Output.of(settings));
        }

        public IntegrationAccountDataflowsDatabricksDataObservabilityQualityMonitoringArgs build() {
            return $;
        }
    }

}
