// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Inputs
{

    public sealed class ActionConnectionHttpTokenAuthUrlParameterGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// URL parameter name. String length must be at least 1.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// URL parameter value. String length must be at least 1.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public ActionConnectionHttpTokenAuthUrlParameterGetArgs()
        {
        }
        public static new ActionConnectionHttpTokenAuthUrlParameterGetArgs Empty => new ActionConnectionHttpTokenAuthUrlParameterGetArgs();
    }
}
