// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Inputs
{

    public sealed class DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The query to use for this widget. **Deprecated.** Use queries and formulas instead.
        /// </summary>
        [Input("apmQuery")]
        public Input<Inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillApmQueryGetArgs>? ApmQuery { get; set; }

        [Input("formulas")]
        private InputList<Inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillFormulaGetArgs>? _formulas;

        /// <summary>
        /// A list of formulas to use in the widget.
        /// </summary>
        public InputList<Inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillFormulaGetArgs> Formulas
        {
            get => _formulas ?? (_formulas = new InputList<Inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillFormulaGetArgs>());
            set => _formulas = value;
        }

        /// <summary>
        /// The query to use for this widget. **Deprecated.** Use queries and formulas instead.
        /// </summary>
        [Input("logQuery")]
        public Input<Inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillLogQueryGetArgs>? LogQuery { get; set; }

        /// <summary>
        /// The process query to use in the widget. The structure of this block is described below. **Deprecated.** Use queries and formulas instead.
        /// </summary>
        [Input("processQuery")]
        public Input<Inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillProcessQueryGetArgs>? ProcessQuery { get; set; }

        /// <summary>
        /// The metric query to use for this widget. **Deprecated.** Use queries and formulas instead.
        /// </summary>
        [Input("q")]
        public Input<string>? Q { get; set; }

        [Input("queries")]
        private InputList<Inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryGetArgs>? _queries;

        /// <summary>
        /// A list of queries to use in the widget.
        /// </summary>
        public InputList<Inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryGetArgs> Queries
        {
            get => _queries ?? (_queries = new InputList<Inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillQueryGetArgs>());
            set => _queries = value;
        }

        /// <summary>
        /// The query to use for this widget. **Deprecated.** Use queries and formulas instead.
        /// </summary>
        [Input("rumQuery")]
        public Input<Inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillRumQueryGetArgs>? RumQuery { get; set; }

        /// <summary>
        /// The query to use for this widget. **Deprecated.** Use queries and formulas instead.
        /// </summary>
        [Input("securityQuery")]
        public Input<Inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillSecurityQueryGetArgs>? SecurityQuery { get; set; }

        public DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillGetArgs()
        {
        }
        public static new DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillGetArgs Empty => new DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillGetArgs();
    }
}
