// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Inputs
{

    public sealed class DashboardV2WidgetTreemapDefinitionRequestSortArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The number of items to limit the widget to.
        /// </summary>
        [Input("count")]
        public Input<int>? Count { get; set; }

        [Input("orderBies")]
        private InputList<Inputs.DashboardV2WidgetTreemapDefinitionRequestSortOrderByArgs>? _orderBies;

        /// <summary>
        /// The list of items to sort the widget by.
        /// </summary>
        public InputList<Inputs.DashboardV2WidgetTreemapDefinitionRequestSortOrderByArgs> OrderBies
        {
            get => _orderBies ?? (_orderBies = new InputList<Inputs.DashboardV2WidgetTreemapDefinitionRequestSortOrderByArgs>());
            set => _orderBies = value;
        }

        public DashboardV2WidgetTreemapDefinitionRequestSortArgs()
        {
        }
        public static new DashboardV2WidgetTreemapDefinitionRequestSortArgs Empty => new DashboardV2WidgetTreemapDefinitionRequestSortArgs();
    }
}
