// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Inputs
{

    public sealed class DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestChildEnrichmentQueryUserJourneyQuerySearchFiltersArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Product Analytics audience filters.
        /// </summary>
        [Input("audienceFilters")]
        public Input<Inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestChildEnrichmentQueryUserJourneyQuerySearchFiltersAudienceFiltersArgs>? AudienceFilters { get; set; }

        [Input("graphFilters")]
        private InputList<Inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestChildEnrichmentQueryUserJourneyQuerySearchFiltersGraphFilterArgs>? _graphFilters;

        /// <summary>
        /// Graph filters for the user journey search.
        /// </summary>
        public InputList<Inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestChildEnrichmentQueryUserJourneyQuerySearchFiltersGraphFilterArgs> GraphFilters
        {
            get => _graphFilters ?? (_graphFilters = new InputList<Inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestChildEnrichmentQueryUserJourneyQuerySearchFiltersGraphFilterArgs>());
            set => _graphFilters = value;
        }

        /// <summary>
        /// String filter for the user journey search.
        /// </summary>
        [Input("stringFilter")]
        public Input<string>? StringFilter { get; set; }

        public DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestChildEnrichmentQueryUserJourneyQuerySearchFiltersArgs()
        {
        }
        public static new DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestChildEnrichmentQueryUserJourneyQuerySearchFiltersArgs Empty => new DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestChildEnrichmentQueryUserJourneyQuerySearchFiltersArgs();
    }
}
