// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Inputs
{

    public sealed class DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionChangeDefinitionRequestQueryRetentionQuerySearchCohortCriteriaTimeIntervalArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Type of cohort time interval. Valid values are `Calendar`.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        /// <summary>
        /// Calendar interval used to build the cohort.
        /// </summary>
        [Input("value", required: true)]
        public Input<Inputs.DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionChangeDefinitionRequestQueryRetentionQuerySearchCohortCriteriaTimeIntervalValueArgs> Value { get; set; } = null!;

        public DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionChangeDefinitionRequestQueryRetentionQuerySearchCohortCriteriaTimeIntervalArgs()
        {
        }
        public static new DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionChangeDefinitionRequestQueryRetentionQuerySearchCohortCriteriaTimeIntervalArgs Empty => new DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionChangeDefinitionRequestQueryRetentionQuerySearchCohortCriteriaTimeIntervalArgs();
    }
}
