// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Inputs
{

    public sealed class DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillFormulaNumberFormatUnitGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Canonical Units
        /// </summary>
        [Input("canonical")]
        public Input<Inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillFormulaNumberFormatUnitCanonicalGetArgs>? Canonical { get; set; }

        /// <summary>
        /// Use custom (non canonical metrics)
        /// </summary>
        [Input("custom")]
        public Input<Inputs.DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillFormulaNumberFormatUnitCustomGetArgs>? Custom { get; set; }

        public DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillFormulaNumberFormatUnitGetArgs()
        {
        }
        public static new DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillFormulaNumberFormatUnitGetArgs Empty => new DashboardV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestFillFormulaNumberFormatUnitGetArgs();
    }
}
