// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Inputs
{

    public sealed class DashboardWidgetGroupDefinitionWidgetHostmapDefinitionRequestGetArgs : Pulumi.ResourceArgs
    {
        [Input("fills")]
        private InputList<Inputs.DashboardWidgetGroupDefinitionWidgetHostmapDefinitionRequestFillGetArgs>? _fills;
        public InputList<Inputs.DashboardWidgetGroupDefinitionWidgetHostmapDefinitionRequestFillGetArgs> Fills
        {
            get => _fills ?? (_fills = new InputList<Inputs.DashboardWidgetGroupDefinitionWidgetHostmapDefinitionRequestFillGetArgs>());
            set => _fills = value;
        }

        [Input("sizes")]
        private InputList<Inputs.DashboardWidgetGroupDefinitionWidgetHostmapDefinitionRequestSizeGetArgs>? _sizes;
        public InputList<Inputs.DashboardWidgetGroupDefinitionWidgetHostmapDefinitionRequestSizeGetArgs> Sizes
        {
            get => _sizes ?? (_sizes = new InputList<Inputs.DashboardWidgetGroupDefinitionWidgetHostmapDefinitionRequestSizeGetArgs>());
            set => _sizes = value;
        }

        public DashboardWidgetGroupDefinitionWidgetHostmapDefinitionRequestGetArgs()
        {
        }
    }
}
