// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Inputs
{

    public sealed class DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionToplistDefinitionRequestSortOrderByGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Sort by a formula value.
        /// </summary>
        [Input("formulaSort")]
        public Input<Inputs.DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionToplistDefinitionRequestSortOrderByFormulaSortGetArgs>? FormulaSort { get; set; }

        /// <summary>
        /// Sort by a group (tag) value.
        /// </summary>
        [Input("groupSort")]
        public Input<Inputs.DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionToplistDefinitionRequestSortOrderByGroupSortGetArgs>? GroupSort { get; set; }

        public DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionToplistDefinitionRequestSortOrderByGetArgs()
        {
        }
        public static new DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionToplistDefinitionRequestSortOrderByGetArgs Empty => new DashboardV2WidgetSplitGraphDefinitionSourceWidgetDefinitionToplistDefinitionRequestSortOrderByGetArgs();
    }
}
