// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Inputs
{

    public sealed class DashboardV2WidgetScatterplotDefinitionRequestYFormulaNumberFormatUnitCustomArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Unit label
        /// </summary>
        [Input("label", required: true)]
        public Input<string> Label { get; set; } = null!;

        public DashboardV2WidgetScatterplotDefinitionRequestYFormulaNumberFormatUnitCustomArgs()
        {
        }
        public static new DashboardV2WidgetScatterplotDefinitionRequestYFormulaNumberFormatUnitCustomArgs Empty => new DashboardV2WidgetScatterplotDefinitionRequestYFormulaNumberFormatUnitCustomArgs();
    }
}
