// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Inputs
{

    public sealed class DashboardV2WidgetHostmapDefinitionRequestSizeQueryProductAnalyticsExtendedQueryArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Product Analytics audience filters.
        /// </summary>
        [Input("audienceFilters")]
        public Input<Inputs.DashboardV2WidgetHostmapDefinitionRequestSizeQueryProductAnalyticsExtendedQueryAudienceFiltersArgs>? AudienceFilters { get; set; }

        /// <summary>
        /// Compute configuration for the Product Analytics Extended query.
        /// </summary>
        [Input("compute", required: true)]
        public Input<Inputs.DashboardV2WidgetHostmapDefinitionRequestSizeQueryProductAnalyticsExtendedQueryComputeArgs> Compute { get; set; } = null!;

        /// <summary>
        /// Data source for Product Analytics Extended queries. Valid values are `ProductAnalyticsExtended`.
        /// </summary>
        [Input("dataSource", required: true)]
        public Input<string> DataSource { get; set; } = null!;

        [Input("groupBies")]
        private InputList<Inputs.DashboardV2WidgetHostmapDefinitionRequestSizeQueryProductAnalyticsExtendedQueryGroupByArgs>? _groupBies;

        /// <summary>
        /// Group by configuration for the Product Analytics Extended query.
        /// </summary>
        public InputList<Inputs.DashboardV2WidgetHostmapDefinitionRequestSizeQueryProductAnalyticsExtendedQueryGroupByArgs> GroupBies
        {
            get => _groupBies ?? (_groupBies = new InputList<Inputs.DashboardV2WidgetHostmapDefinitionRequestSizeQueryProductAnalyticsExtendedQueryGroupByArgs>());
            set => _groupBies = value;
        }

        [Input("indexes")]
        private InputList<string>? _indexes;

        /// <summary>
        /// Event indexes to query. Use `*` to query all indexes.
        /// </summary>
        public InputList<string> Indexes
        {
            get => _indexes ?? (_indexes = new InputList<string>());
            set => _indexes = value;
        }

        /// <summary>
        /// Name of the query for use in formulas.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Base Product Analytics event query.
        /// </summary>
        [Input("query", required: true)]
        public Input<Inputs.DashboardV2WidgetHostmapDefinitionRequestSizeQueryProductAnalyticsExtendedQueryQueryArgs> Query { get; set; } = null!;

        public DashboardV2WidgetHostmapDefinitionRequestSizeQueryProductAnalyticsExtendedQueryArgs()
        {
        }
        public static new DashboardV2WidgetHostmapDefinitionRequestSizeQueryProductAnalyticsExtendedQueryArgs Empty => new DashboardV2WidgetHostmapDefinitionRequestSizeQueryProductAnalyticsExtendedQueryArgs();
    }
}
