// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Inputs
{

    public sealed class GetActionConnectionDatadogArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Configuration for Datadog API and application key authentication
        /// </summary>
        [Input("apiKey")]
        public Inputs.GetActionConnectionDatadogApiKeyArgs? ApiKey { get; set; }

        public GetActionConnectionDatadogArgs()
        {
        }
        public static new GetActionConnectionDatadogArgs Empty => new GetActionConnectionDatadogArgs();
    }
}
