// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Inputs
{

    public sealed class LogsCustomDestinationMicrosoftSentinelDestinationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Client ID from the Datadog Azure Integration.
        /// </summary>
        [Input("clientId", required: true)]
        public Input<string> ClientId { get; set; } = null!;

        /// <summary>
        /// Azure Data Collection Endpoint.
        /// </summary>
        [Input("dataCollectionEndpoint", required: true)]
        public Input<string> DataCollectionEndpoint { get; set; } = null!;

        /// <summary>
        /// Azure Data Collection Rule ID.
        /// </summary>
        [Input("dataCollectionRuleId", required: true)]
        public Input<string> DataCollectionRuleId { get; set; } = null!;

        /// <summary>
        /// Azure stream name.
        /// </summary>
        [Input("streamName", required: true)]
        public Input<string> StreamName { get; set; } = null!;

        /// <summary>
        /// Tenant ID from the Datadog Azure Integration.
        /// </summary>
        [Input("tenantId", required: true)]
        public Input<string> TenantId { get; set; } = null!;

        public LogsCustomDestinationMicrosoftSentinelDestinationArgs()
        {
        }
        public static new LogsCustomDestinationMicrosoftSentinelDestinationArgs Empty => new LogsCustomDestinationMicrosoftSentinelDestinationArgs();
    }
}
