// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Inputs
{

    public sealed class LogsCustomPipelineProcessorPipelineProcessorArrayMapProcessorGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// If the processor is enabled.
        /// </summary>
        [Input("isEnabled")]
        public Input<bool>? IsEnabled { get; set; }

        /// <summary>
        /// Name of the processor.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Remove or preserve the source array after processing. Defaults to `True`.
        /// </summary>
        [Input("preserveSource")]
        public Input<bool>? PreserveSource { get; set; }

        [Input("processors", required: true)]
        private InputList<Inputs.LogsCustomPipelineProcessorPipelineProcessorArrayMapProcessorProcessorGetArgs>? _processors;

        /// <summary>
        /// Sub-processors applied to each element. Allowed types: attribute*remapper, string*builder*processor, arithmetic*processor, category*processor.
        /// </summary>
        public InputList<Inputs.LogsCustomPipelineProcessorPipelineProcessorArrayMapProcessorProcessorGetArgs> Processors
        {
            get => _processors ?? (_processors = new InputList<Inputs.LogsCustomPipelineProcessorPipelineProcessorArrayMapProcessorProcessorGetArgs>());
            set => _processors = value;
        }

        /// <summary>
        /// Attribute path of the source array.
        /// </summary>
        [Input("source", required: true)]
        public Input<string> Source { get; set; } = null!;

        /// <summary>
        /// Attribute path of the output array.
        /// </summary>
        [Input("target", required: true)]
        public Input<string> Target { get; set; } = null!;

        public LogsCustomPipelineProcessorPipelineProcessorArrayMapProcessorGetArgs()
        {
        }
        public static new LogsCustomPipelineProcessorPipelineProcessorArrayMapProcessorGetArgs Empty => new LogsCustomPipelineProcessorPipelineProcessorArrayMapProcessorGetArgs();
    }
}
