// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Inputs
{

    public sealed class MonitorVariablesAggregateAugmentedQueryArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Events augment query. Do not set `AugmentReferenceTable` in the same block.
        /// </summary>
        [Input("augmentEventQuery")]
        public Input<Inputs.MonitorVariablesAggregateAugmentedQueryAugmentEventQueryArgs>? AugmentEventQuery { get; set; }

        /// <summary>
        /// Reference table augment query. Do not set `AugmentEventQuery` in the same block.
        /// </summary>
        [Input("augmentReferenceTable")]
        public Input<Inputs.MonitorVariablesAggregateAugmentedQueryAugmentReferenceTableArgs>? AugmentReferenceTable { get; set; }

        /// <summary>
        /// Events base query. Do not set `BaseMetricsQuery` in the same block.
        /// </summary>
        [Input("baseEventQuery")]
        public Input<Inputs.MonitorVariablesAggregateAugmentedQueryBaseEventQueryArgs>? BaseEventQuery { get; set; }

        /// <summary>
        /// Metrics base query. Do not set `BaseEventQuery` in the same block.
        /// </summary>
        [Input("baseMetricsQuery")]
        public Input<Inputs.MonitorVariablesAggregateAugmentedQueryBaseMetricsQueryArgs>? BaseMetricsQuery { get; set; }

        [Input("computes", required: true)]
        private InputList<Inputs.MonitorVariablesAggregateAugmentedQueryComputeArgs>? _computes;

        /// <summary>
        /// Compute aggregations for the aggregate-augmented query.
        /// </summary>
        public InputList<Inputs.MonitorVariablesAggregateAugmentedQueryComputeArgs> Computes
        {
            get => _computes ?? (_computes = new InputList<Inputs.MonitorVariablesAggregateAugmentedQueryComputeArgs>());
            set => _computes = value;
        }

        /// <summary>
        /// The data source for aggregate-augmented composite queries. Must be `AggregateAugmentedQuery`. Valid values are `AggregateAugmentedQuery`.
        /// </summary>
        [Input("dataSource", required: true)]
        public Input<string> DataSource { get; set; } = null!;

        [Input("groupBies", required: true)]
        private InputList<Inputs.MonitorVariablesAggregateAugmentedQueryGroupByArgs>? _groupBies;

        /// <summary>
        /// Group by options for the aggregate-augmented query. At least one block is required.
        /// </summary>
        public InputList<Inputs.MonitorVariablesAggregateAugmentedQueryGroupByArgs> GroupBies
        {
            get => _groupBies ?? (_groupBies = new InputList<Inputs.MonitorVariablesAggregateAugmentedQueryGroupByArgs>());
            set => _groupBies = value;
        }

        /// <summary>
        /// Join condition between augment and base queries.
        /// </summary>
        [Input("joinCondition", required: true)]
        public Input<Inputs.MonitorVariablesAggregateAugmentedQueryJoinConditionArgs> JoinCondition { get; set; } = null!;

        /// <summary>
        /// Name of the query for use in formulas.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public MonitorVariablesAggregateAugmentedQueryArgs()
        {
        }
        public static new MonitorVariablesAggregateAugmentedQueryArgs Empty => new MonitorVariablesAggregateAugmentedQueryArgs();
    }
}
