// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Inputs
{

    public sealed class ObservabilityPipelineConfigSourcesSocketGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Defines the framing method for incoming messages.
        /// </summary>
        [Input("framing")]
        public Input<Inputs.ObservabilityPipelineConfigSourcesSocketFramingGetArgs>? Framing { get; set; }

        /// <summary>
        /// The unique identifier for this component.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// The protocol used to receive logs. Valid values are `tcp`, `udp`.
        /// </summary>
        [Input("mode", required: true)]
        public Input<string> Mode { get; set; } = null!;

        /// <summary>
        /// Configuration for enabling TLS encryption between the pipeline component and external services.
        /// </summary>
        [Input("tls")]
        public Input<Inputs.ObservabilityPipelineConfigSourcesSocketTlsGetArgs>? Tls { get; set; }

        public ObservabilityPipelineConfigSourcesSocketGetArgs()
        {
        }
        public static new ObservabilityPipelineConfigSourcesSocketGetArgs Empty => new ObservabilityPipelineConfigSourcesSocketGetArgs();
    }
}
