// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Inputs
{

    public sealed class ObservabilityPipelineConfigDestinationElasticsearchAuthGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the environment variable or secret that holds the Elasticsearch password (used when `Strategy` is `Basic`).
        /// </summary>
        [Input("passwordKey")]
        public Input<string>? PasswordKey { get; set; }

        /// <summary>
        /// The authentication strategy to use. Valid values are `Basic`, `Aws`.
        /// </summary>
        [Input("strategy", required: true)]
        public Input<string> Strategy { get; set; } = null!;

        /// <summary>
        /// Name of the environment variable or secret that holds the Elasticsearch username (used when `Strategy` is `Basic`).
        /// </summary>
        [Input("usernameKey")]
        public Input<string>? UsernameKey { get; set; }

        public ObservabilityPipelineConfigDestinationElasticsearchAuthGetArgs()
        {
        }
        public static new ObservabilityPipelineConfigDestinationElasticsearchAuthGetArgs Empty => new ObservabilityPipelineConfigDestinationElasticsearchAuthGetArgs();
    }
}
