// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Inputs
{

    public sealed class PowerpackV2WidgetToplistDefinitionRequestQueryProductAnalyticsExtendedQueryAudienceFiltersArgs : global::Pulumi.ResourceArgs
    {
        [Input("accounts")]
        private InputList<Inputs.PowerpackV2WidgetToplistDefinitionRequestQueryProductAnalyticsExtendedQueryAudienceFiltersAccountArgs>? _accounts;

        /// <summary>
        /// Product Analytics audience account subqueries.
        /// </summary>
        public InputList<Inputs.PowerpackV2WidgetToplistDefinitionRequestQueryProductAnalyticsExtendedQueryAudienceFiltersAccountArgs> Accounts
        {
            get => _accounts ?? (_accounts = new InputList<Inputs.PowerpackV2WidgetToplistDefinitionRequestQueryProductAnalyticsExtendedQueryAudienceFiltersAccountArgs>());
            set => _accounts = value;
        }

        /// <summary>
        /// An optional filter condition applied to the audience subquery.
        /// </summary>
        [Input("filterCondition")]
        public Input<string>? FilterCondition { get; set; }

        [Input("segments")]
        private InputList<Inputs.PowerpackV2WidgetToplistDefinitionRequestQueryProductAnalyticsExtendedQueryAudienceFiltersSegmentArgs>? _segments;

        /// <summary>
        /// Product Analytics audience segment subqueries.
        /// </summary>
        public InputList<Inputs.PowerpackV2WidgetToplistDefinitionRequestQueryProductAnalyticsExtendedQueryAudienceFiltersSegmentArgs> Segments
        {
            get => _segments ?? (_segments = new InputList<Inputs.PowerpackV2WidgetToplistDefinitionRequestQueryProductAnalyticsExtendedQueryAudienceFiltersSegmentArgs>());
            set => _segments = value;
        }

        [Input("users")]
        private InputList<Inputs.PowerpackV2WidgetToplistDefinitionRequestQueryProductAnalyticsExtendedQueryAudienceFiltersUserArgs>? _users;

        /// <summary>
        /// Product Analytics audience user subqueries.
        /// </summary>
        public InputList<Inputs.PowerpackV2WidgetToplistDefinitionRequestQueryProductAnalyticsExtendedQueryAudienceFiltersUserArgs> Users
        {
            get => _users ?? (_users = new InputList<Inputs.PowerpackV2WidgetToplistDefinitionRequestQueryProductAnalyticsExtendedQueryAudienceFiltersUserArgs>());
            set => _users = value;
        }

        public PowerpackV2WidgetToplistDefinitionRequestQueryProductAnalyticsExtendedQueryAudienceFiltersArgs()
        {
        }
        public static new PowerpackV2WidgetToplistDefinitionRequestQueryProductAnalyticsExtendedQueryAudienceFiltersArgs Empty => new PowerpackV2WidgetToplistDefinitionRequestQueryProductAnalyticsExtendedQueryAudienceFiltersArgs();
    }
}
