// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Inputs
{

    public sealed class PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYApmQueryGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// `ComputeQuery` or `MultiCompute` is required. The map keys are listed below.
        /// </summary>
        [Input("computeQuery")]
        public Input<Inputs.PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYApmQueryComputeQueryGetArgs>? ComputeQuery { get; set; }

        [Input("groupBies")]
        private InputList<Inputs.PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYApmQueryGroupByGetArgs>? _groupBies;

        /// <summary>
        /// Multiple `GroupBy` blocks are allowed using the structure below.
        /// </summary>
        public InputList<Inputs.PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYApmQueryGroupByGetArgs> GroupBies
        {
            get => _groupBies ?? (_groupBies = new InputList<Inputs.PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYApmQueryGroupByGetArgs>());
            set => _groupBies = value;
        }

        /// <summary>
        /// A comma separated-list of index names. Use `*` to query all indexes at once. [Multiple Indexes](https://docs.datadoghq.com/logs/indexes/#multiple-indexes).
        /// </summary>
        [Input("index", required: true)]
        public Input<string> Index { get; set; } = null!;

        [Input("multiComputes")]
        private InputList<Inputs.PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYApmQueryMultiComputeGetArgs>? _multiComputes;

        /// <summary>
        /// `ComputeQuery` or `MultiCompute` is required. Multiple `MultiCompute` blocks are allowed using the structure below.
        /// </summary>
        public InputList<Inputs.PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYApmQueryMultiComputeGetArgs> MultiComputes
        {
            get => _multiComputes ?? (_multiComputes = new InputList<Inputs.PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYApmQueryMultiComputeGetArgs>());
            set => _multiComputes = value;
        }

        /// <summary>
        /// The search query to use.
        /// </summary>
        [Input("searchQuery")]
        public Input<string>? SearchQuery { get; set; }

        public PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYApmQueryGetArgs()
        {
        }
        public static new PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYApmQueryGetArgs Empty => new PowerpackV2WidgetGroupDefinitionWidgetScatterplotDefinitionRequestYApmQueryGetArgs();
    }
}
