// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Inputs
{

    public sealed class PowerpackV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestEnrichmentQueryRetentionQuerySearchReturnCriteriaBaseQuerySearchGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Product Analytics event search query used to filter views or actions.
        /// </summary>
        [Input("query", required: true)]
        public Input<string> Query { get; set; } = null!;

        public PowerpackV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestEnrichmentQueryRetentionQuerySearchReturnCriteriaBaseQuerySearchGetArgs()
        {
        }
        public static new PowerpackV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestEnrichmentQueryRetentionQuerySearchReturnCriteriaBaseQuerySearchGetArgs Empty => new PowerpackV2WidgetGroupDefinitionWidgetHostmapDefinitionRequestEnrichmentQueryRetentionQuerySearchReturnCriteriaBaseQuerySearchGetArgs();
    }
}
