// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Inputs
{

    public sealed class SyntheticsTestRequestClientCertificateArgs : global::Pulumi.ResourceArgs
    {
        [Input("cert", required: true)]
        public Input<Inputs.SyntheticsTestRequestClientCertificateCertArgs> Cert { get; set; } = null!;

        [Input("key", required: true)]
        public Input<Inputs.SyntheticsTestRequestClientCertificateKeyArgs> Key { get; set; } = null!;

        public SyntheticsTestRequestClientCertificateArgs()
        {
        }
        public static new SyntheticsTestRequestClientCertificateArgs Empty => new SyntheticsTestRequestClientCertificateArgs();
    }
}
