// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Datadog.Inputs
{

    public sealed class SyntheticsTestMobileOptionsListMonitorOptionsGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A message to include with a re-notification.
        /// </summary>
        [Input("escalationMessage")]
        public Input<string>? EscalationMessage { get; set; }

        /// <summary>
        /// Valid values are `show_all`, `hide_all`, `hide_query`, `hide_handles`.
        /// </summary>
        [Input("notificationPresetName")]
        public Input<string>? NotificationPresetName { get; set; }

        /// <summary>
        /// Specify a renotification frequency in minutes. Values available by default are `0`, `10`, `20`, `30`, `40`, `50`, `60`, `90`, `120`, `180`, `240`, `300`, `360`, `720`, `1440`. Defaults to `0`.
        /// </summary>
        [Input("renotifyInterval")]
        public Input<int>? RenotifyInterval { get; set; }

        /// <summary>
        /// The number of times a monitor renotifies. It can only be set if `renotify_interval` is set.
        /// </summary>
        [Input("renotifyOccurrences")]
        public Input<int>? RenotifyOccurrences { get; set; }

        public SyntheticsTestMobileOptionsListMonitorOptionsGetArgs()
        {
        }
        public static new SyntheticsTestMobileOptionsListMonitorOptionsGetArgs Empty => new SyntheticsTestMobileOptionsListMonitorOptionsGetArgs();
    }
}
