// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Use this data source to retrieve a Datadog RUM Application.
 */
export function getRumApplication(args?: GetRumApplicationArgs, opts?: pulumi.InvokeOptions): Promise<GetRumApplicationResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("datadog:index/getRumApplication:getRumApplication", {
        "id": args.id,
        "nameFilter": args.nameFilter,
        "typeFilter": args.typeFilter,
    }, opts);
}

/**
 * A collection of arguments for invoking getRumApplication.
 */
export interface GetRumApplicationArgs {
    /**
     * ID of the RUM application. Cannot be used with name and type filters.
     */
    id?: string;
    /**
     * The name used to search for a RUM application.
     */
    nameFilter?: string;
    /**
     * The type used to search for a RUM application.
     */
    typeFilter?: string;
}

/**
 * A collection of values returned by getRumApplication.
 */
export interface GetRumApplicationResult {
    /**
     * The client token.
     */
    readonly clientToken: string;
    /**
     * ID of the RUM application. Cannot be used with name and type filters.
     */
    readonly id: string;
    /**
     * Name of the RUM application.
     */
    readonly name: string;
    /**
     * The name used to search for a RUM application.
     */
    readonly nameFilter?: string;
    /**
     * Type of the RUM application. Supported values are `browser`, `ios`, `android`, `react-native`, `flutter`.
     */
    readonly type: string;
    /**
     * The type used to search for a RUM application.
     */
    readonly typeFilter?: string;
}
/**
 * Use this data source to retrieve a Datadog RUM Application.
 */
export function getRumApplicationOutput(args?: GetRumApplicationOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRumApplicationResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("datadog:index/getRumApplication:getRumApplication", {
        "id": args.id,
        "nameFilter": args.nameFilter,
        "typeFilter": args.typeFilter,
    }, opts);
}

/**
 * A collection of arguments for invoking getRumApplication.
 */
export interface GetRumApplicationOutputArgs {
    /**
     * ID of the RUM application. Cannot be used with name and type filters.
     */
    id?: pulumi.Input<string>;
    /**
     * The name used to search for a RUM application.
     */
    nameFilter?: pulumi.Input<string>;
    /**
     * The type used to search for a RUM application.
     */
    typeFilter?: pulumi.Input<string>;
}
